// ── Knowledge Registry (Phase 5) ────────────────────────────
// One canonical registry. Every field the runtime can score, detect, ask
// about, and complete is declared here. The score engine, missing-field
// analyzer, question engine, builder hints, and storefront score ALL derive
// from this registry — nothing is hard-coded in a UI or a service.

import type { KnowledgeField } from "./types";

const hasText = (value: unknown): boolean => typeof value === "string" && value.trim().length > 0;
const minCount = (value: unknown, min: number): boolean =>
  Array.isArray(value) && value.length >= min;

const ratioComplete = (present: number, total: number, target = 3): boolean =>
  total === 0 || present >= Math.min(target, total);

/**
 * Universal fields — applicable to every entity type. Pack-specific fields
 * are declared in category-packs.ts and may replace universal ones.
 */
export const KNOWLEDGE_REGISTRY: KnowledgeField[] = [
  // ── Identity ──────────────────────────────────────────────
  {
    id: "identity.name",
    label: "Display Name",
    category: "identity",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: false,
    generationUsage: ["hero", "seo", "storefront"],
    href: "/admin/settings",
    hint: "Visitors need to know who you are — set your display name.",
    source: "aggregate",
    complete: (s) => s.identity.name.trim().length >= 2,
    value: (s) => s.identity.name,
  },
  {
    id: "identity.avatar",
    label: "Profile Photo",
    category: "media",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: false,
    generationUsage: ["hero", "trust"],
    href: "/admin/settings",
    hint: "A profile photo builds immediate trust — faces convert.",
    source: "aggregate",
    complete: (s) => Boolean(s.identity.avatarUrl),
  },
  {
    id: "identity.banner",
    label: "Banner Image",
    category: "media",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: false,
    generationUsage: ["hero"],
    href: "/admin/settings",
    hint: "A banner makes your hero section feel premium.",
    source: "aggregate",
    complete: (s) => Boolean(s.identity.bannerUrl),
  },

  // ── Brand ─────────────────────────────────────────────────
  {
    id: "brand.tagline",
    label: "Tagline",
    category: "brand",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: true,
    generationUsage: ["hero", "seo", "brand"],
    href: "/admin/settings",
    hint: "One line that summarises what you do — used in your hero.",
    source: "aggregate",
    validation: { minLength: 3 },
    complete: (s) => s.identity.tagline.trim().length >= 3,
    value: (s) => s.identity.tagline,
  },
  {
    id: "brand.bio",
    label: "Bio / About",
    category: "brand",
    required: true,
    optional: false,
    priority: 2,
    aiRelevance: true,
    generationUsage: ["hero", "about", "seo", "trust"],
    href: "/admin/settings",
    hint: "Tell your story — a strong bio builds trust and ranks in search.",
    source: "aggregate",
    validation: { minLength: 30 },
    complete: (s) => s.identity.bio.trim().length >= 30,
    value: (s) => s.identity.bio,
  },
  {
    id: "brand.logo",
    label: "Logo",
    category: "brand",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: false,
    generationUsage: ["brand", "storefront"],
    href: "/admin/settings",
    hint: "A logo (or your profile photo) makes your brand memorable.",
    source: "aggregate",
    complete: (s) => Boolean(s.brand.logoUrl) || Boolean(s.identity.avatarUrl),
  },
  {
    id: "brand.colors",
    label: "Brand Colors",
    category: "brand",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: false,
    generationUsage: ["theme", "brand"],
    href: "/admin/appearance",
    hint: "Custom colors make the site feel like your brand.",
    source: "setting",
    complete: (s) => s.brand.customTheme,
  },
  {
    id: "brand.mission",
    label: "Mission",
    category: "brand",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: true,
    generationUsage: ["about", "brand"],
    href: "/admin/knowledge",
    hint: "Why do you do what you do? A mission adds depth to your about.",
    source: "declared",
    validation: { minLength: 10 },
    complete: (s) => hasText(s.declared.brand_mission),
    value: (s) => s.declared.brand_mission,
  },
  {
    id: "brand.voice",
    label: "Brand Voice",
    category: "brand",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: false,
    generationUsage: ["copy", "brand"],
    href: "/admin/knowledge",
    hint: "Professional, casual or playful — describe your tone.",
    source: "declared",
    complete: (s) => hasText(s.declared.brand_voice),
    value: (s) => s.declared.brand_voice,
  },

  // ── Business ──────────────────────────────────────────────
  {
    id: "business.domain",
    label: "Custom Domain",
    category: "business",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: false,
    generationUsage: ["seo", "platform"],
    href: "/admin/settings/domain",
    hint: "Connect a custom domain for a professional web presence.",
    source: "setting",
    complete: (s) => Boolean(s.business.customDomain),
  },
  {
    id: "business.hours",
    label: "Business Hours",
    category: "business",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: false,
    generationUsage: ["contact", "booking"],
    href: "/admin/knowledge",
    hint: "When are you available? Helps visitors and bookings.",
    source: "declared",
    validation: { minCount: 1 },
    complete: (s) => (Array.isArray(s.contact.businessHours) && s.contact.businessHours.length > 0) || hasText(s.declared.business_hours),
    value: (s) => s.contact.businessHours.length > 0 ? s.contact.businessHours : s.declared.business_hours,
  },

  // ── Commerce ──────────────────────────────────────────────
  {
    id: "commerce.products",
    label: "Products",
    category: "commerce",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: false,
    generationUsage: ["products", "commerce"],
    href: "/admin/products",
    hint: "Give fans something to buy — at least one product or offer.",
    source: "table",
    complete: (s) => s.commerce.productCount >= 1,
  },
  {
    id: "commerce.productDescriptions",
    label: "Product Descriptions",
    category: "commerce",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: true,
    generationUsage: ["products", "seo"],
    href: "/admin/products",
    hint: "Describe what each product is so buyers understand the value.",
    source: "table",
    complete: (s) => ratioComplete(s.commerce.productsWithDescription, s.commerce.productCount),
  },
  {
    id: "commerce.productImages",
    label: "Product Images",
    category: "commerce",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: false,
    generationUsage: ["products"],
    href: "/admin/products",
    hint: "Products with photos sell far better.",
    source: "table",
    complete: (s) => ratioComplete(s.commerce.productsWithImage, s.commerce.productCount),
  },
  {
    id: "commerce.pricing",
    label: "Pricing",
    category: "commerce",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: false,
    generationUsage: ["products", "commerce", "checkout"],
    href: "/admin/products",
    hint: "List a price for every offer so visitors can buy.",
    source: "table",
    complete: (s) => s.commerce.offersPriced >= Math.min(3, Math.max(1, s.commerce.offerCount)),
  },
  {
    id: "commerce.services",
    label: "Services",
    category: "commerce",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: false,
    generationUsage: ["services", "commerce"],
    href: "/admin/services",
    hint: "Offer coaching or services you sell by session.",
    source: "table",
    complete: (s) => s.commerce.serviceCount >= 1,
  },
  {
    id: "commerce.courses",
    label: "Courses",
    category: "commerce",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: false,
    generationUsage: ["courses", "commerce"],
    href: "/admin/courses",
    hint: "Sell your knowledge as a course.",
    source: "table",
    complete: (s) => s.commerce.courseCount >= 1,
  },
  {
    id: "commerce.bookings",
    label: "Bookings",
    category: "commerce",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: false,
    generationUsage: ["booking", "commerce"],
    href: "/admin/bookings",
    hint: "Enable bookings so visitors can reserve your time.",
    source: "table",
    complete: (s) => s.commerce.bookingCount >= 1,
  },

  // ── Content ───────────────────────────────────────────────
  {
    id: "content.gallery",
    label: "Portfolio / Gallery",
    category: "content",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: false,
    generationUsage: ["gallery", "content"],
    href: "/admin/gallery",
    hint: "Add at least 3 images for a stronger portfolio.",
    source: "table",
    complete: (s) => s.content.galleryCount >= 3,
  },
  {
    id: "content.galleryQuality",
    label: "Gallery Quality",
    category: "content",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: false,
    generationUsage: ["gallery", "accessibility"],
    href: "/admin/gallery",
    hint: "Add titles and alt text to your gallery images.",
    source: "table",
    complete: (s) =>
      s.content.galleryCount === 0 ||
      (s.content.galleryCount >= 1 &&
        ratioComplete(s.content.galleryWithTitle, s.content.galleryCount) &&
        ratioComplete(s.content.galleryWithAltText, s.content.galleryCount)),
  },
  {
    id: "content.faq",
    label: "FAQ",
    category: "content",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: true,
    generationUsage: ["faq", "seo"],
    href: "/admin/faq",
    hint: "Answer common questions to reduce friction.",
    source: "table",
    complete: (s) => s.content.faqCount >= 3,
  },
  {
    id: "content.feed",
    label: "Content Feed",
    category: "content",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: false,
    generationUsage: ["contentFeed"],
    href: "/admin/settings/content",
    hint: "Pull in your latest posts so the site always feels fresh.",
    source: "table",
    complete: (s) => s.content.feedCount >= 3,
  },

  // ── Trust ─────────────────────────────────────────────────
  {
    id: "trust.testimonials",
    label: "Testimonials",
    category: "trust",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: false,
    generationUsage: ["testimonials", "trust"],
    href: "/admin/testimonials",
    hint: "Social proof convinces undecided visitors — add real reviews.",
    source: "table",
    complete: (s) => s.trust.testimonialCount >= 3,
  },
  {
    id: "trust.timeline",
    label: "Milestones / Timeline",
    category: "trust",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: false,
    generationUsage: ["timeline", "trust"],
    href: "/admin/milestones",
    hint: "Share your journey with milestones and achievements.",
    source: "table",
    complete: (s) => s.trust.timelineCount >= 2,
  },
  {
    id: "trust.achievements",
    label: "Achievements",
    category: "trust",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: true,
    generationUsage: ["timeline", "about", "trust"],
    href: "/admin/knowledge",
    hint: "Awards, results and highlights build instant credibility.",
    source: "declared",
    validation: { minLength: 10 },
    complete: (s) => hasText(s.declared.trust_achievements),
    value: (s) => s.declared.trust_achievements,
  },

  // ── Media ─────────────────────────────────────────────────
  {
    id: "media.heroMedia",
    label: "Hero Media",
    category: "media",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: false,
    generationUsage: ["hero"],
    href: "/admin/settings",
    hint: "Add a hero video or image — it is the first thing visitors see.",
    source: "aggregate",
    complete: (s) => s.media.heroMediaPresent,
  },
  {
    id: "media.heroTitle",
    label: "Hero Title",
    category: "media",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: true,
    generationUsage: ["hero", "seo"],
    href: "/admin/settings",
    hint: "A clear hero title captures attention in seconds.",
    source: "aggregate",
    complete: (s) => s.media.heroTitlePresent,
  },

  // ── SEO ───────────────────────────────────────────────────
  {
    id: "seo.title",
    label: "SEO Title",
    category: "seo",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: true,
    generationUsage: ["seo"],
    href: "/admin/seo",
    hint: "Optimise your page title for search engines.",
    source: "setting",
    validation: { minLength: 10 },
    complete: (s) => s.seo.title.trim().length >= 10,
    value: (s) => s.seo.title,
  },
  {
    id: "seo.description",
    label: "SEO Description",
    category: "seo",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: true,
    generationUsage: ["seo"],
    href: "/admin/seo",
    hint: "Summarise your page in 1–2 sentences for search results.",
    source: "setting",
    validation: { minLength: 30 },
    complete: (s) => s.seo.description.trim().length >= 30,
    value: (s) => s.seo.description,
  },
  {
    id: "seo.keywords",
    label: "SEO Keywords",
    category: "seo",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: true,
    generationUsage: ["seo"],
    href: "/admin/knowledge",
    hint: "Keywords people use to find you.",
    source: "declared",
    validation: { minCount: 3 },
    complete: (s) => minCount(s.declared.seo_keywords, 3),
    value: (s) => s.declared.seo_keywords,
  },

  // ── Contact ───────────────────────────────────────────────
  {
    id: "contact.email",
    label: "Contact Email",
    category: "contact",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: false,
    generationUsage: ["contact", "trust"],
    href: "/admin/profile",
    hint: "A public contact email makes you reachable.",
    source: "setting",
    complete: (s) => s.contact.email.includes("@"),
    value: (s) => s.contact.email,
  },
  {
    id: "contact.phone",
    label: "Phone",
    category: "contact",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: false,
    generationUsage: ["contact"],
    href: "/admin/profile",
    hint: "A phone number helps local customers reach you.",
    source: "setting",
    complete: (s) => s.contact.phone.trim().length >= 7,
    value: (s) => s.contact.phone,
  },
  {
    id: "contact.location",
    label: "Location",
    category: "contact",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: false,
    generationUsage: ["contact", "seo"],
    href: "/admin/profile",
    hint: "Where are you based? Useful for local search.",
    source: "setting",
    complete: (s) => s.contact.location.trim().length >= 2,
    value: (s) => s.contact.location,
  },
  {
    id: "contact.languages",
    label: "Languages",
    category: "contact",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: false,
    generationUsage: ["contact", "audience"],
    href: "/admin/profile",
    hint: "Which languages do you serve your audience in?",
    source: "setting",
    validation: { minCount: 1 },
    complete: (s) => s.contact.languages.length >= 1,
    value: (s) => s.contact.languages,
  },

  // ── Social ────────────────────────────────────────────────
  {
    id: "social.links",
    label: "Social Links",
    category: "social",
    required: true,
    optional: false,
    priority: 1,
    aiRelevance: false,
    generationUsage: ["social", "trust"],
    href: "/admin/settings",
    hint: "Link your social profiles so visitors can follow you.",
    source: "aggregate",
    complete: (s) => s.social.socialLinkCount >= 1,
  },
  {
    id: "social.primaryPlatform",
    label: "Primary Platform",
    category: "social",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: false,
    generationUsage: ["social", "content"],
    href: "/admin/knowledge",
    hint: "Where do you post most? (YouTube, Instagram, Twitch…).",
    source: "declared",
    complete: (s) => s.social.primaryPlatform.trim().length >= 2,
    value: (s) => s.social.primaryPlatform,
  },
  {
    id: "social.feed",
    label: "Connected Social Feed",
    category: "social",
    required: false,
    optional: true,
    priority: 2,
    aiRelevance: false,
    generationUsage: ["contentFeed"],
    href: "/admin/settings/content",
    hint: "Connect a social feed to keep the site fresh automatically.",
    source: "table",
    complete: (s) => s.social.feedConnected,
  },
  {
    id: "social.affiliateLinks",
    label: "Affiliate Links",
    category: "social",
    required: false,
    optional: true,
    priority: 3,
    aiRelevance: false,
    generationUsage: ["links", "commerce"],
    href: "/admin/links",
    hint: "Recommend products you love and earn commission.",
    source: "table",
    complete: (s) => s.social.affiliateLinkCount >= 1,
  },
];

export function getField(fieldId: string): KnowledgeField | undefined {
  return KNOWLEDGE_REGISTRY.find((f) => f.id === fieldId);
}

export function getFieldByDeclaredKey(key: string): KnowledgeField | undefined {
  return KNOWLEDGE_REGISTRY.find((f) => f.source === "declared" && declaredKeyFor(f.id) === key);
}

/** Maps a field id to its `knowledge_completion` fact key. */
export function declaredKeyFor(fieldId: string): string {
  return fieldId.replace(/\./g, "_");
}
