import type { ModuleDefinition } from "@/lib/module/types";

export const heroModule: ModuleDefinition = {
  identity: {
    id: "com.creatos.hero",
    name: "Hero",
    version: "1.0.0",
    domain: "content",
    description: "Full-viewport hero banner with video, image, CTAs, and live badge",
    author: { type: "platform", id: "com.creatos", name: "CreatorOS" },
    icon: "Layout",
    category: "content",
    tags: ["hero", "banner", "video", "cta"],
  },
  composition: {
    capabilities: [],
    serviceContracts: [],
    dependencies: [],
  },
  surfaces: {
    supported: [
      { surfaceId: "website", rendererPath: "@/app/[domain]/_components/hero-banner#HeroBanner", interactive: true, streaming: false, cacheable: true },
      { surfaceId: "website_preview", rendererPath: "@/components/public/VideoHero", interactive: true, streaming: false, cacheable: false },
      { surfaceId: "admin_panel", rendererPath: "@/app/admin/settings/_components/settings-live-preview#SettingsLivePreview", interactive: true, streaming: false, cacheable: false },
    ],
    dataLoaderPath: "@/modules/hero/data-loader#heroDataLoader",
    defaultSurface: "website",
  },
  configuration: {
    schema: {},
    defaults: {},
    settingsKey: "module_config:com.creatos.hero",
    overridableByCreator: ["videoUrl", "posterUrl", "ctaText", "ctaLink", "subtitle"],
    lockedByTheme: ["heroOverlay", "heroHeight"],
  },
  theme: {
    tokensConsumed: [
      "color.accent.primary",
      "color.surface.primary",
      "typography.scale.4xl",
      "spacing.sectionGap",
    ],
    variantSlots: ["HeroBanner", "HeroOverlay"],
  },
  ai: {
    contextProviderPath: "@/modules/hero/ai-context#heroAiContext",
    aiCapabilities: [],
  },
  permissions: {
    requiredPlanTiers: ["STARTER", "PRO"],
    featureFlags: [],
    agencyPermissions: [],
    minimumRole: "ADMIN",
  },
  events: { published: [], subscribed: [] },
  marketplace: {
    previewImages: [],
    tags: ["hero", "banner"],
    pricing: { model: "free" },
    compatibleThemes: ["*"],
    minPlatformVersion: "1.0.0",
    changelog: "Initial release",
    documentationUrl: null,
  },
  metadata: { displayName: "Hero", icon: "Layout", category: "content", description: "Full-viewport hero banner", defaultProps: {}, propertySchema: [], capabilities: { draggable: true, duplicatable: true, deletable: false, editable: true, resizable: false, copyable: true }, tags: ["hero"] },
  manifest: {
    id: "com.creatos.hero",
    name: "Hero",
    version: "1.0.0",
    domain: "content",
    description: "Full-viewport hero banner with video, image, CTAs, and live badge",
    author: { type: "platform", id: "com.creatos", name: "CreatorOS" },
    license: "MIT",
    icon: "Layout",
    category: "content",
    tags: ["hero", "banner", "video", "cta"],
    minPlatformVersion: "1.0.0",
    pricing: { model: "free" },
    previewImages: [],
    documentationUrl: null,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
};
