// ── Goal Registry (Phase 1) ─────────────────────────────────
// One canonical registry of creator goals. Every goal declares what it means,
// which sections/navigation it favours, which commerce surface it leads with,
// which knowledge it depends on, and which milestones/suggestions it implies.
// The recommendation engine, composition, navigation, dashboard, builder
// hints, success milestones and alignment score ALL derive from this registry.

import type { GoalDefinition } from "./types";

export const GOAL_REGISTRY: GoalDefinition[] = [
  {
    id: "GET_BOOKINGS",
    label: "Get Bookings",
    description: "Turn visitors into booked appointments, reservations or sessions.",
    icon: "CalendarCheck",
    category: "conversion",
    priority: 1,
    applicableTypes: ["fitness", "restaurant", "photography", "designer"],
    supportedSections: ["hero", "pricing", "contact", "testimonials", "faq"],
    sectionOrderHint: ["hero", "pricing", "testimonials", "faq", "contact"],
    navigationPriority: ["contact", "testimonials", "faq"],
    dashboardRecommendations: ["Enable bookings", "List your pricing", "Add testimonials"],
    commercePriority: "bookings",
    seoPriority: "local",
    supportingKnowledge: ["commerce.bookings", "commerce.pricing", "business.hours", "contact.phone", "trust.testimonials"],
    milestonePath: [
      { id: "bookings_configured", label: "Enable bookings", description: "Let customers book your time", action: "Create Booking", href: "/admin/bookings", category: "setup", done: (c) => c.bookings > 0 },
      { id: "pricing_listed", label: "List your pricing", description: "Show what a session costs", action: "Add Pricing", href: "/admin/products", category: "setup", done: (c) => c.products > 0 },
      { id: "first_booking", label: "First booking", description: "Someone books your time", action: "View Bookings", href: "/admin/bookings", category: "conversion", done: (c) => c.bookings >= 5 || c.orders > 0 },
      { id: "bookings_5", label: "5 bookings", description: "Consistent demand", action: "View Bookings", href: "/admin/bookings", category: "growth", done: (c) => c.bookings >= 5 },
      { id: "bookings_25", label: "25 bookings", description: "A busy calendar", action: "View Bookings", href: "/admin/bookings", category: "growth", done: (c) => c.bookings >= 25 },
    ],
    suggestions: [
      { knowledgeField: "commerce.bookings", moduleId: "contact", title: "Enable bookings", message: "Let visitors reserve your time directly from the site.", href: "/admin/bookings", severity: "critical" },
      { knowledgeField: "commerce.pricing", moduleId: "pricing", title: "Show pricing", message: "List what a booking costs to remove friction.", href: "/admin/products", severity: "warning" },
      { knowledgeField: "trust.testimonials", moduleId: "testimonials", title: "Add testimonials", message: "Social proof convinces visitors to book.", href: "/admin/testimonials", severity: "info" },
    ],
  },

  {
    id: "SELL_PRODUCTS",
    label: "Sell Products",
    description: "Grow product sales — merch, digital goods or physical items.",
    icon: "ShoppingBag",
    category: "revenue",
    priority: 2,
    applicableTypes: [],
    supportedSections: ["hero", "products", "testimonials", "faq", "newsletter"],
    sectionOrderHint: ["hero", "products", "testimonials", "faq", "newsletter"],
    navigationPriority: ["products", "testimonials"],
    dashboardRecommendations: ["Add a product", "Add product photos", "Add reviews"],
    commercePriority: "products",
    seoPriority: "commerce",
    supportingKnowledge: ["commerce.products", "commerce.productImages", "commerce.productDescriptions", "commerce.pricing", "trust.testimonials"],
    milestonePath: [
      { id: "first_product", label: "Create your first product", description: "Give fans something to buy", action: "Create Product", href: "/admin/products", category: "setup", done: (c) => c.products > 0 },
      { id: "first_sale", label: "First sale", description: "Someone buys from you", action: "View Orders", href: "/admin/orders", category: "conversion", done: (c) => c.orders > 0 },
      { id: "orders_10", label: "10 orders", description: "Repeatable demand", action: "View Orders", href: "/admin/orders", category: "growth", done: (c) => c.orders >= 10 },
      { id: "orders_100", label: "100 orders", description: "A real storefront", action: "View Orders", href: "/admin/orders", category: "growth", done: (c) => c.orders >= 100 },
    ],
    suggestions: [
      { knowledgeField: "commerce.products", moduleId: "products", title: "Add products", message: "No products yet — give visitors something to buy.", href: "/admin/products", severity: "critical" },
      { knowledgeField: "commerce.productImages", moduleId: "products", title: "Add product photos", message: "Products with images sell far better.", href: "/admin/products", severity: "warning" },
      { knowledgeField: "trust.testimonials", moduleId: "testimonials", title: "Add reviews", message: "Reviews help convert hesitant buyers.", href: "/admin/testimonials", severity: "info" },
    ],
  },

  {
    id: "SELL_COURSES",
    label: "Sell Courses",
    description: "Package your knowledge into sellable courses.",
    icon: "BookOpen",
    category: "revenue",
    priority: 3,
    applicableTypes: ["education", "fitness", "creator"],
    supportedSections: ["hero", "courses", "testimonials", "faq", "newsletter"],
    sectionOrderHint: ["hero", "courses", "testimonials", "faq", "newsletter"],
    navigationPriority: ["courses", "testimonials"],
    dashboardRecommendations: ["Add a course", "Add a syllabus", "Add student reviews"],
    commercePriority: "courses",
    seoPriority: "content",
    supportingKnowledge: ["commerce.courses", "commerce.pricing", "trust.testimonials", "content.faq"],
    milestonePath: [
      { id: "first_course", label: "Publish a course", description: "Turn knowledge into a product", action: "Add Course", href: "/admin/courses", category: "setup", done: (c) => c.courses > 0 },
      { id: "first_student", label: "First student", description: "Someone enrols", action: "View Orders", href: "/admin/orders", category: "conversion", done: (c) => c.orders > 0 },
      { id: "students_25", label: "25 students", description: "Course momentum", action: "View Orders", href: "/admin/orders", category: "growth", done: (c) => c.orders >= 25 },
    ],
    suggestions: [
      { knowledgeField: "commerce.courses", moduleId: "courses", title: "Publish a course", message: "Sell your knowledge as a course.", href: "/admin/courses", severity: "critical" },
      { knowledgeField: "content.faq", moduleId: "faq", title: "Answer course FAQs", message: "Reduce hesitancy before enrolment.", href: "/admin/faq", severity: "info" },
    ],
  },

  {
    id: "SELL_SERVICES",
    label: "Sell Services",
    description: "Offer coaching, consulting or service packages.",
    icon: "Briefcase",
    category: "revenue",
    priority: 4,
    applicableTypes: ["business", "designer", "fitness", "photography"],
    supportedSections: ["hero", "services", "pricing", "testimonials", "contact"],
    sectionOrderHint: ["hero", "services", "pricing", "testimonials", "contact"],
    navigationPriority: ["services", "contact"],
    dashboardRecommendations: ["Add a service", "Add pricing", "Add testimonials"],
    commercePriority: "services",
    seoPriority: "portfolio",
    supportingKnowledge: ["commerce.services", "commerce.pricing", "trust.testimonials", "contact.email"],
    milestonePath: [
      { id: "first_service", label: "List a service", description: "Define what you sell", action: "Add Service", href: "/admin/services", category: "setup", done: (c) => c.services > 0 },
      { id: "first_client", label: "First client", description: "Someone hires you", action: "View Orders", href: "/admin/orders", category: "conversion", done: (c) => c.orders > 0 },
      { id: "clients_10", label: "10 clients", description: "Steady pipeline", action: "View Orders", href: "/admin/orders", category: "growth", done: (c) => c.orders >= 10 },
    ],
    suggestions: [
      { knowledgeField: "commerce.services", moduleId: "services", title: "List your services", message: "Show exactly what you offer.", href: "/admin/services", severity: "critical" },
      { knowledgeField: "contact.email", moduleId: "contact", title: "Add contact email", message: "Make it easy for clients to reach you.", href: "/admin/profile", severity: "info" },
    ],
  },

  {
    id: "BUILD_EMAIL_LIST",
    label: "Build Email List",
    description: "Grow an owned audience via newsletter signups.",
    icon: "Mail",
    category: "audience",
    priority: 5,
    applicableTypes: [],
    supportedSections: ["hero", "newsletter", "products", "testimonials"],
    sectionOrderHint: ["hero", "newsletter", "products", "testimonials"],
    navigationPriority: ["newsletter"],
    dashboardRecommendations: ["Add newsletter block", "Add a lead magnet", "Add footer signup"],
    commercePriority: null,
    seoPriority: "content",
    supportingKnowledge: ["identity.name", "brand.tagline", "brand.bio", "social.links"],
    milestonePath: [
      { id: "newsletter_block", label: "Add a newsletter block", description: "Capture email signups", action: "Add Newsletter", href: "/builder", category: "setup", done: () => false },
      { id: "brand_story", label: "Write your story", description: "Give people a reason to subscribe", action: "Edit Bio", href: "/admin/settings", category: "setup", done: (c) => c.timeline > 0 || c.testimonials > 0 },
      { id: "first_100", label: "First 100 subscribers", description: "Owned audience begins", action: "Share Site", href: "/admin/analytics", category: "growth", done: () => false },
    ],
    suggestions: [
      { knowledgeField: "brand.bio", moduleId: "hero", title: "Write your story", message: "Give visitors a reason to subscribe.", href: "/admin/settings", severity: "info" },
      { knowledgeField: "social.links", moduleId: "links", title: "Link your socials", message: "Cross-promote your newsletter everywhere.", href: "/admin/settings", severity: "info" },
    ],
  },

  {
    id: "GROW_YOUTUBE",
    label: "Grow YouTube",
    description: "Grow a YouTube audience and content reach.",
    icon: "Youtube",
    category: "audience",
    priority: 6,
    applicableTypes: ["creator", "education", "gaming", "music", "food", "lifestyle", "sports", "travel"],
    supportedSections: ["hero", "contentFeed", "testimonials", "newsletter"],
    sectionOrderHint: ["hero", "contentFeed", "testimonials", "newsletter"],
    navigationPriority: ["contentFeed", "testimonials"],
    dashboardRecommendations: ["Connect your channel", "Add content feed", "Add CTA"],
    commercePriority: null,
    seoPriority: "content",
    supportingKnowledge: ["social.primaryPlatform", "social.feed", "content.feed", "social.links"],
    milestonePath: [
      { id: "channel_connected", label: "Connect your channel", description: "Link your YouTube presence", action: "Connect Channel", href: "/admin/settings/content", category: "setup", done: (c) => c.contentFeed > 0 },
      { id: "feed_live", label: "Feed on your site", description: "Latest uploads appear automatically", action: "View Feed", href: "/admin/settings/content", category: "setup", done: (c) => c.contentFeed >= 3 },
      { id: "milestone_10k", label: "10k subscribers", description: "Community milestone", action: "View Analytics", href: "/admin/analytics", category: "growth", done: () => false },
    ],
    suggestions: [
      { knowledgeField: "social.feed", moduleId: "contentFeed", title: "Connect your feed", message: "Keep your site fresh with your latest content.", href: "/admin/settings/content", severity: "warning" },
      { knowledgeField: "social.primaryPlatform", moduleId: "hero", title: "Name your platform", message: "Tell visitors where you post most.", href: "/admin/knowledge", severity: "info" },
    ],
  },

  {
    id: "BUILD_COMMUNITY",
    label: "Build Community",
    description: "Grow a loyal, engaged community around your brand.",
    icon: "Users",
    category: "engagement",
    priority: 7,
    applicableTypes: ["education", "creator", "gaming"],
    supportedSections: ["hero", "newsletter", "contentFeed", "testimonials"],
    sectionOrderHint: ["hero", "contentFeed", "newsletter", "testimonials"],
    navigationPriority: ["contentFeed", "newsletter"],
    dashboardRecommendations: ["Add newsletter", "Add content feed", "Add community CTA"],
    commercePriority: null,
    seoPriority: "content",
    supportingKnowledge: ["social.links", "content.feed", "brand.mission", "content.faq"],
    milestonePath: [
      { id: "community_hub", label: "Connect community channels", description: "Link Discord / newsletter / feed", action: "Add Links", href: "/admin/links", category: "setup", done: (c) => c.contentFeed > 0 },
      { id: "engaged_100", label: "100 engaged members", description: "Active community", action: "View Analytics", href: "/admin/analytics", category: "growth", done: () => false },
    ],
    suggestions: [
      { knowledgeField: "content.feed", moduleId: "contentFeed", title: "Show community content", message: "Surface member posts and conversations.", href: "/admin/settings/content", severity: "info" },
      { knowledgeField: "brand.mission", moduleId: "hero", title: "Share your mission", message: "People join communities with a purpose.", href: "/admin/knowledge", severity: "info" },
    ],
  },

  {
    id: "SHOW_PORTFOLIO",
    label: "Show Portfolio",
    description: "Present work and proof to attract new business.",
    icon: "Images",
    category: "brand",
    priority: 8,
    applicableTypes: ["photography", "designer", "art", "film", "travel"],
    supportedSections: ["hero", "gallery", "timeline", "testimonials", "contact"],
    sectionOrderHint: ["hero", "gallery", "timeline", "testimonials", "contact"],
    navigationPriority: ["gallery", "timeline", "testimonials"],
    dashboardRecommendations: ["Upload portfolio", "Add alt text", "Add timeline"],
    commercePriority: null,
    seoPriority: "portfolio",
    supportingKnowledge: ["content.gallery", "content.galleryQuality", "identity.banner", "trust.timeline"],
    milestonePath: [
      { id: "first_work", label: "Upload your work", description: "Add portfolio images", action: "Upload Images", href: "/admin/gallery", category: "setup", done: (c) => c.gallery > 0 },
      { id: "portfolio_3", label: "3+ pieces", description: "A credible portfolio", action: "Upload Images", href: "/admin/gallery", category: "setup", done: (c) => c.gallery >= 3 },
      { id: "first_client", label: "First client", description: "Work converts", action: "View Orders", href: "/admin/orders", category: "conversion", done: (c) => c.orders > 0 },
    ],
    suggestions: [
      { knowledgeField: "content.gallery", moduleId: "gallery", title: "Build your portfolio", message: "Add at least 3 images for a strong first impression.", href: "/admin/gallery", severity: "critical" },
      { knowledgeField: "content.galleryQuality", moduleId: "gallery", title: "Add alt text", message: "Improves accessibility and search.", href: "/admin/gallery", severity: "info" },
      { knowledgeField: "trust.timeline", moduleId: "timeline", title: "Add milestones", message: "Show your journey and credibility.", href: "/admin/milestones", severity: "info" },
    ],
  },

  {
    id: "GENERATE_LEADS",
    label: "Generate Leads",
    description: "Capture enquiries and sales-ready leads.",
    icon: "Target",
    category: "conversion",
    priority: 9,
    applicableTypes: ["business", "designer", "photography"],
    supportedSections: ["hero", "services", "contact", "testimonials"],
    sectionOrderHint: ["hero", "services", "contact", "testimonials"],
    navigationPriority: ["contact", "services"],
    dashboardRecommendations: ["Add contact form", "Add services", "Add CTA"],
    commercePriority: "services",
    seoPriority: "portfolio",
    supportingKnowledge: ["commerce.services", "contact.email", "contact.phone", "trust.testimonials"],
    milestonePath: [
      { id: "lead_form", label: "Add a lead form", description: "Capture enquiries", action: "Add Contact", href: "/builder", category: "setup", done: () => false },
      { id: "first_lead", label: "First enquiry", description: "Someone reaches out", action: "View Messages", href: "/admin/messages", category: "conversion", done: (c) => c.orders > 0 },
      { id: "leads_10", label: "10 enquiries", description: "Steady lead flow", action: "View Messages", href: "/admin/messages", category: "growth", done: (c) => c.orders >= 10 },
    ],
    suggestions: [
      { knowledgeField: "contact.email", moduleId: "contact", title: "Add contact email", message: "Make it easy for leads to reach you.", href: "/admin/profile", severity: "warning" },
      { knowledgeField: "commerce.services", moduleId: "services", title: "List services", message: "Show leads what they can hire you for.", href: "/admin/services", severity: "info" },
    ],
  },

  {
    id: "PROMOTE_EVENTS",
    label: "Promote Events",
    description: "Sell tickets and promote events, workshops or shows.",
    icon: "CalendarClock",
    category: "conversion",
    priority: 10,
    applicableTypes: ["restaurant", "music", "comedy", "film", "sports"],
    supportedSections: ["hero", "products", "gallery", "testimonials"],
    sectionOrderHint: ["hero", "products", "gallery", "testimonials"],
    navigationPriority: ["products", "gallery"],
    dashboardRecommendations: ["Add event tickets", "Add event gallery", "Add CTA"],
    commercePriority: "products",
    seoPriority: "local",
    supportingKnowledge: ["commerce.products", "commerce.pricing", "content.gallery", "trust.testimonials"],
    milestonePath: [
      { id: "tickets_live", label: "List event tickets", description: "Sell tickets on your site", action: "Add Product", href: "/admin/products", category: "setup", done: (c) => c.products > 0 },
      { id: "first_attendee", label: "First attendee", description: "Ticket sold", action: "View Orders", href: "/admin/orders", category: "conversion", done: (c) => c.orders > 0 },
    ],
    suggestions: [
      { knowledgeField: "commerce.products", moduleId: "products", title: "List tickets", message: "Sell event tickets directly.", href: "/admin/products", severity: "critical" },
      { knowledgeField: "content.gallery", moduleId: "gallery", title: "Show past events", message: "Photos of past events build excitement.", href: "/admin/gallery", severity: "info" },
    ],
  },

  {
    id: "FIND_CLIENTS",
    label: "Find Clients",
    description: "Attract inbound clients for your agency or freelance work.",
    icon: "Handshake",
    category: "conversion",
    priority: 11,
    applicableTypes: ["business", "designer", "photography", "art"],
    supportedSections: ["hero", "services", "gallery", "testimonials", "contact"],
    sectionOrderHint: ["hero", "services", "gallery", "testimonials", "contact"],
    navigationPriority: ["services", "gallery", "contact"],
    dashboardRecommendations: ["Add services", "Add portfolio", "Add testimonials"],
    commercePriority: "services",
    seoPriority: "portfolio",
    supportingKnowledge: ["commerce.services", "content.gallery", "trust.testimonials", "contact.email"],
    milestonePath: [
      { id: "offer_clear", label: "Define your offer", description: "List what you sell", action: "Add Service", href: "/admin/services", category: "setup", done: (c) => c.services > 0 },
      { id: "proof", label: "Add proof", description: "Portfolio + testimonials", action: "Add Work", href: "/admin/gallery", category: "setup", done: (c) => c.gallery > 0 && c.testimonials > 0 },
      { id: "first_client", label: "First client", description: "Inbound client", action: "View Orders", href: "/admin/orders", category: "conversion", done: (c) => c.orders > 0 },
    ],
    suggestions: [
      { knowledgeField: "commerce.services", moduleId: "services", title: "Define your offer", message: "Be crystal clear about what you sell.", href: "/admin/services", severity: "critical" },
      { knowledgeField: "content.gallery", moduleId: "gallery", title: "Show proof", message: "Work samples convert hesitant clients.", href: "/admin/gallery", severity: "warning" },
    ],
  },

  {
    id: "BUILD_BRAND",
    label: "Build Brand",
    description: "Build a distinctive brand that people remember.",
    icon: "Palette",
    category: "brand",
    priority: 12,
    applicableTypes: ["creator", "business", "celebrity"],
    supportedSections: ["hero", "gallery", "testimonials", "timeline"],
    sectionOrderHint: ["hero", "gallery", "testimonials", "timeline"],
    navigationPriority: ["gallery", "testimonials"],
    dashboardRecommendations: ["Upload a logo", "Set brand colors", "Write your bio"],
    commercePriority: null,
    seoPriority: "trust",
    supportingKnowledge: ["brand.logo", "brand.colors", "brand.bio", "identity.avatar", "brand.mission"],
    milestonePath: [
      { id: "logo", label: "Upload your logo", description: "Brand your storefront", action: "Upload Logo", href: "/admin/appearance", category: "setup", done: (c) => c.gallery > 0 },
      { id: "colors", label: "Set brand colors", description: "Make the site feel yours", action: "Edit Theme", href: "/admin/appearance", category: "setup", done: (c) => c.timeline > 0 },
      { id: "story", label: "Tell your story", description: "A memorable bio", action: "Edit Bio", href: "/admin/settings", category: "setup", done: (c) => c.testimonials > 0 },
    ],
    suggestions: [
      { knowledgeField: "brand.colors", moduleId: "hero", title: "Set brand colors", message: "Custom colors make the site feel like your brand.", href: "/admin/appearance", severity: "info" },
      { knowledgeField: "brand.mission", moduleId: "hero", title: "Add a mission", message: "Give your brand a reason to exist.", href: "/admin/knowledge", severity: "info" },
    ],
  },

  {
    id: "INCREASE_TRUST",
    label: "Increase Trust",
    description: "Add proof that makes visitors believe you.",
    icon: "ShieldCheck",
    category: "brand",
    priority: 13,
    applicableTypes: [],
    supportedSections: ["hero", "testimonials", "timeline", "faq"],
    sectionOrderHint: ["hero", "testimonials", "timeline", "faq"],
    navigationPriority: ["testimonials", "timeline", "faq"],
    dashboardRecommendations: ["Add testimonials", "Add timeline", "Add achievements"],
    commercePriority: null,
    seoPriority: "trust",
    supportingKnowledge: ["trust.testimonials", "trust.timeline", "trust.achievements", "brand.bio"],
    milestonePath: [
      { id: "testimonials", label: "Add testimonials", description: "Social proof", action: "Add Testimonial", href: "/admin/testimonials", category: "setup", done: (c) => c.testimonials > 0 },
      { id: "timeline", label: "Add milestones", description: "Your journey", action: "Add Timeline", href: "/admin/milestones", category: "setup", done: (c) => c.timeline > 0 },
      { id: "proof_3", label: "3+ testimonials", description: "Strong social proof", action: "Add Testimonials", href: "/admin/testimonials", category: "setup", done: (c) => c.testimonials >= 3 },
    ],
    suggestions: [
      { knowledgeField: "trust.testimonials", moduleId: "testimonials", title: "Add testimonials", message: "Social proof convinces undecided visitors.", href: "/admin/testimonials", severity: "warning" },
      { knowledgeField: "trust.timeline", moduleId: "timeline", title: "Add milestones", message: "Share your journey with milestones.", href: "/admin/milestones", severity: "info" },
      { knowledgeField: "trust.achievements", moduleId: "timeline", title: "Upload achievements", message: "Awards and results build instant credibility.", href: "/admin/knowledge", severity: "info" },
    ],
  },

  {
    id: "MONETIZE_CONTENT",
    label: "Monetize Content",
    description: "Turn content into revenue via affiliates, merch and sponsors.",
    icon: "Coins",
    category: "revenue",
    priority: 14,
    applicableTypes: ["creator", "gaming", "music", "lifestyle", "comedy", "sports"],
    supportedSections: ["hero", "products", "links", "newsletter", "contentFeed"],
    sectionOrderHint: ["hero", "products", "links", "newsletter", "contentFeed"],
    navigationPriority: ["links", "products"],
    dashboardRecommendations: ["Add affiliate links", "Add products", "Add newsletter"],
    commercePriority: "products",
    seoPriority: "commerce",
    supportingKnowledge: ["social.affiliateLinks", "commerce.products", "social.links", "content.feed"],
    milestonePath: [
      { id: "affiliate_links", label: "Add affiliate links", description: "Earn from recommendations", action: "Add Links", href: "/admin/links", category: "setup", done: (c) => c.affiliateLinks > 0 },
      { id: "first_product", label: "Add a product", description: "Merch or digital goods", action: "Create Product", href: "/admin/products", category: "setup", done: (c) => c.products > 0 },
      { id: "first_revenue", label: "First revenue", description: "Affiliate or product sale", action: "View Orders", href: "/admin/orders", category: "conversion", done: (c) => c.orders > 0 },
    ],
    suggestions: [
      { knowledgeField: "social.affiliateLinks", moduleId: "links", title: "Add affiliate links", message: "Earn commission on things you recommend.", href: "/admin/links", severity: "warning" },
      { knowledgeField: "commerce.products", moduleId: "products", title: "Add a product", message: "Merch and digital goods monetise your audience.", href: "/admin/products", severity: "info" },
    ],
  },
];

const REGISTRY_BY_ID = new Map(GOAL_REGISTRY.map((g) => [g.id, g]));

export function getGoal(goalId: string): GoalDefinition | undefined {
  return REGISTRY_BY_ID.get(goalId as GoalDefinition["id"]);
}

export function isKnownGoal(goalId: string): boolean {
  return REGISTRY_BY_ID.has(goalId as GoalDefinition["id"]);
}
