import type { GoldenCreatorEntry, GoldenDatasetConfig } from "./types";

const GOLDEN_CREATORS: GoldenCreatorEntry[] = [
  {
    id: "golden-gaming-001",
    name: "Wiffey Gamer",
    platform: "youtube",
    url: "https://www.youtube.com/@Wiffeygamer_8",
    expectedPersonaId: "persona-gaming-streamer",
    expectedPersonaName: "Gaming Streamer",
    expectedBusinessModel: "community",
    expectedCreatorStage: "growing",
    expectedContentStyle: "entertainment",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "exploring",
    expectedConfidence: 0.82,
    tags: ["gaming", "entertainment", "live-streaming"],
  },
  {
    id: "golden-education-001",
    name: "Class 9 Maths & Science",
    platform: "youtube",
    url: "https://www.youtube.com/@Class9MathsScience",
    expectedPersonaId: "persona-educator",
    expectedPersonaName: "Educator",
    expectedBusinessModel: "education",
    expectedCreatorStage: "growing",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "none",
    expectedConfidence: 0.91,
    tags: ["education", "math", "science"],
  },
  {
    id: "golden-entertainment-001",
    name: "Farah Khan",
    platform: "youtube",
    url: "https://www.youtube.com/@FarahKhanK",
    expectedPersonaId: "persona-lifestyle-creator",
    expectedPersonaName: "Lifestyle Creator",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "established",
    expectedContentStyle: "entertainment",
    expectedAudienceType: "general",
    expectedBrandStrength: "strong",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    tags: ["entertainment", "lifestyle", "vlogging"],
  },
  {
    id: "golden-comedy-001",
    name: "Samay Raina",
    platform: "youtube",
    url: "https://www.youtube.com/@SamayRainaOfficial",
    expectedPersonaId: "persona-entertainer",
    expectedPersonaName: "Entertainer",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "established",
    expectedContentStyle: "entertainment",
    expectedAudienceType: "general",
    expectedBrandStrength: "strong",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.88,
    tags: ["comedy", "entertainment", "standup"],
  },
  // IMPLEMENTATION-32 ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â expanded regression dataset (representative anchors).
  {
    id: "golden-athlete-001",
    name: "Cristiano Ronaldo",
    platform: "instagram",
    url: "https://www.instagram.com/cristiano",
    expectedPersonaId: "sports_athlete",
    expectedPersonaName: "Athlete",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "inspirational",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.95,
    expectedEntityType: "athlete",
    expectedPrimaryNiche: "sports",
    tags: ["athlete", "sports", "celebrity"],
  },
  {
    id: "golden-entertainment-002",
    name: "MrBeast",
    platform: "youtube",
    url: "https://www.youtube.com/@MrBeast",
    expectedPersonaId: "finance_educator",
    expectedPersonaName: "Finance Educator",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "educational",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.6,
    expectedEntityType: "creator",
    expectedPrimaryNiche: "entertainment",
    tags: ["entertainment", "creator", "celebrity"],
  },
  {
    id: "golden-technology-001",
    name: "Fireship",
    platform: "youtube",
    url: "https://www.youtube.com/@Fireship",
    expectedPersonaId: "tech_developer",
    expectedPersonaName: "Developer",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "technical",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "developer",
    expectedPrimaryNiche: "technology",
    tags: ["technology", "developer", "education"],
  },
  {
    id: "golden-brand-001",
    name: "Nike",
    platform: "youtube",
    url: "https://www.youtube.com/@nike",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "promotional",
    expectedAudienceType: "professional",
    expectedBrandStrength: "strong",
    expectedCommerceStage: "scaling",
    expectedConfidence: 0.6,
    expectedEntityType: "brand",
    expectedPrimaryNiche: "sports",
    tags: ["brand", "sports", "retail"],
  },
  {
    id: "golden-brand-002",
    name: "Apple",
    platform: "youtube",
    url: "https://www.youtube.com/@Apple",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "promotional",
    expectedAudienceType: "professional",
    expectedBrandStrength: "strong",
    expectedCommerceStage: "scaling",
    expectedConfidence: 0.6,
    expectedEntityType: "brand",
    expectedPrimaryNiche: "technology",
    tags: ["brand", "technology", "retail"],
  },
  {
    id: "golden-education-002",
    name: "Khan Academy",
    platform: "youtube",
    url: "https://www.youtube.com/@khanacademy",
    expectedPersonaId: "education_course_creator",
    expectedPersonaName: "Course Creator",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "educational",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "educator",
    expectedPrimaryNiche: "education",
    tags: ["education", "learning"],
  },
  {
    id: "golden-restaurant-001",
    name: "SeaShell Restaurant",
    platform: "instagram",
    url: "https://www.instagram.com/seashell",
    expectedPersonaId: "food_restaurant",
    expectedPersonaName: "Restaurant",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "established",
    expectedContentStyle: "promotional",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.95,
    expectedEntityType: "restaurant",
    expectedPrimaryNiche: "food",
    tags: ["restaurant", "food", "local"],
  },
  {
    id: "golden-photographer-001",
    name: "Jane Photography",
    platform: "instagram",
    url: "https://www.instagram.com/jane.shoots",
    expectedPersonaId: "photography_print_seller",
    expectedPersonaName: "Print Seller",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "professional",
    expectedContentStyle: "inspirational",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.95,
    expectedEntityType: "creator",
    expectedPrimaryNiche: "photography",
    tags: ["photography", "creator"],
  },
  {
    id: "golden-coach-001",
    name: "Fit Coach Alex",
    platform: "instagram",
    url: "https://www.instagram.com/fitcoach",
    expectedPersonaId: "fitness_gym",
    expectedPersonaName: "Gym",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "established",
    expectedContentStyle: "promotional",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "coach",
    expectedPrimaryNiche: "fitness",
    tags: ["coach", "fitness", "services"],
  },
  {
    id: "golden-agency-001",
    name: "Creatosa Agency",
    platform: "instagram",
    url: "https://www.instagram.com/creatosa",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "established",
    expectedContentStyle: "entertainment",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.45,
    expectedEntityType: "agency",
    expectedPrimaryNiche: "business",
    tags: ["agency", "business", "services"],
  },
  // IMPLEMENTATION-36 ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â expanded regression dataset (50 representative profiles).
  {
    id: "golden-athlete-002",
    name: "Lionel Messi",
    platform: "instagram",
    url: "https://www.instagram.com/leomessi",
    expectedPersonaId: "sports_athlete",
    expectedPersonaName: "Athlete",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "inspirational",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.95,
    expectedEntityType: "athlete",
    expectedPrimaryNiche: "sports",
    expectedNiches: ["sports", "fitness"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["athlete", "sports", "football"],
  },
  {
    id: "golden-athlete-003",
    name: "Serena Williams",
    platform: "instagram",
    url: "https://www.instagram.com/serenawilliams",
    expectedPersonaId: "sports_athlete",
    expectedPersonaName: "Athlete",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "inspirational",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.95,
    expectedEntityType: "athlete",
    expectedPrimaryNiche: "sports",
    expectedNiches: ["sports", "fitness"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["athlete", "tennis", "sports"],
  },
  {
    id: "golden-technology-002",
    name: "Theo (t3.gg)",
    platform: "youtube",
    url: "https://www.youtube.com/@t3dotgg",
    expectedPersonaId: "tech_developer",
    expectedPersonaName: "Developer",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "professional",
    expectedContentStyle: "technical",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "developer",
    expectedPrimaryNiche: "technology",
    expectedNiches: ["programming", "web_development", "ai"],
    expectedAudience: "developers",
    minimumConfidence: 0.55,
    tags: ["developer", "technology", "web"],
  },
  {
    id: "golden-technology-003",
    name: "The Primeagen",
    platform: "youtube",
    url: "https://www.youtube.com/@ThePrimeagen",
    expectedPersonaId: "tech_developer",
    expectedPersonaName: "Developer",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "professional",
    expectedContentStyle: "technical",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "developer",
    expectedPrimaryNiche: "programming",
    expectedNiches: ["programming", "web_development", "technology"],
    expectedAudience: "developers",
    minimumConfidence: 0.55,
    tags: ["developer", "programming"],
  },
  {
    id: "golden-health-001",
    name: "Dr. Jane Smith",
    platform: "instagram",
    url: "https://www.instagram.com/drjanesmith",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "service_based",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.6,
    expectedEntityType: "doctor",
    expectedPrimaryNiche: "health",
    expectedNiches: ["health", "mental_health"],
    expectedAudience: "professionals",
    minimumConfidence: 0.55,
    tags: ["doctor", "health", "medical"],
  },
  {
    id: "golden-music-001",
    name: "Arijit Singh",
    platform: "youtube",
    url: "https://www.youtube.com/@ArijitSingh",
    expectedPersonaId: "persona-entertainer",
    expectedPersonaName: "Entertainer",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "entertainment",
    expectedAudienceType: "general",
    expectedBrandStrength: "strong",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.88,
    expectedEntityType: "musician",
    expectedPrimaryNiche: "music",
    expectedNiches: ["music", "entertainment"],
    expectedAudience: "students",
    minimumConfidence: 0.55,
    tags: ["music", "singer", "entertainment"],
  },
  {
    id: "golden-teacher-001",
    name: "Math with Mr. Khan",
    platform: "youtube",
    url: "https://www.youtube.com/@MathWithMrKhan",
    expectedPersonaId: "persona-educator",
    expectedPersonaName: "Educator",
    expectedBusinessModel: "education",
    expectedCreatorStage: "growing",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "none",
    expectedConfidence: 0.9,
    expectedEntityType: "teacher",
    expectedPrimaryNiche: "education",
    expectedNiches: ["education", "science"],
    expectedAudience: "students",
    minimumConfidence: 0.55,
    tags: ["teacher", "education", "math"],
  },
  {
    id: "golden-company-001",
    name: "Samsung",
    platform: "youtube",
    url: "https://www.youtube.com/@Samsung",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "promotional",
    expectedAudienceType: "professional",
    expectedBrandStrength: "strong",
    expectedCommerceStage: "scaling",
    expectedConfidence: 0.6,
    expectedEntityType: "company",
    expectedPrimaryNiche: "technology",
    expectedNiches: ["technology", "mobile_development"],
    expectedAudience: "professionals",
    minimumConfidence: 0.55,
    tags: ["company", "technology", "retail"],
  },
  {
    id: "golden-company-002",
    name: "LEGO",
    platform: "youtube",
    url: "https://www.youtube.com/@LEGO",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "promotional",
    expectedAudienceType: "general",
    expectedBrandStrength: "strong",
    expectedCommerceStage: "scaling",
    expectedConfidence: 0.6,
    expectedEntityType: "brand",
    expectedPrimaryNiche: "gaming",
    expectedNiches: ["gaming", "entertainment"],
    expectedAudience: "parents",
    minimumConfidence: 0.55,
    tags: ["brand", "toys", "entertainment"],
  },
  {
    id: "golden-finance-001",
    name: "Stock Market Pro",
    platform: "instagram",
    url: "https://www.instagram.com/stockmarketpro",
    expectedPersonaId: "finance_educator",
    expectedPersonaName: "Finance Educator",
    expectedBusinessModel: "content_monetization",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.8,
    expectedEntityType: "trader",
    expectedPrimaryNiche: "finance",
    expectedNiches: ["finance", "stock market", "forex"],
    expectedAudience: "traders",
    minimumConfidence: 0.55,
    tags: ["finance", "trading", "stocks"],
  },
  {
    id: "golden-finance-002",
    name: "Crypto Daily",
    platform: "youtube",
    url: "https://www.youtube.com/@CryptoDaily",
    expectedPersonaId: "finance_educator",
    expectedPersonaName: "Finance Educator",
    expectedBusinessModel: "content_monetization",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.8,
    expectedEntityType: "trader",
    expectedPrimaryNiche: "crypto",
    expectedNiches: ["crypto", "finance"],
    expectedAudience: "investors",
    minimumConfidence: 0.55,
    tags: ["crypto", "finance"],
  },
  {
    id: "golden-gaming-002",
    name: "Shroud",
    platform: "youtube",
    url: "https://www.youtube.com/@shroud",
    expectedPersonaId: "persona-gaming-streamer",
    expectedPersonaName: "Gaming Streamer",
    expectedBusinessModel: "community",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "entertainment",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.9,
    expectedEntityType: "streamer",
    expectedPrimaryNiche: "gaming",
    expectedNiches: ["gaming", "entertainment"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["gaming", "streamer"],
  },
  {
    id: "golden-travel-001",
    name: "The Travel Guy",
    platform: "youtube",
    url: "https://www.youtube.com/@TheTravelGuy",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Lifestyle Creator",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "established",
    expectedContentStyle: "storytelling",
    expectedAudienceType: "general",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.8,
    expectedEntityType: "creator",
    expectedPrimaryNiche: "travel",
    expectedNiches: ["travel", "lifestyle"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["travel", "lifestyle"],
  },
  {
    id: "golden-beauty-001",
    name: "Glow Beauty Studio",
    platform: "instagram",
    url: "https://www.instagram.com/glowbeautystudio",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Lifestyle Creator",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "established",
    expectedContentStyle: "promotional",
    expectedAudienceType: "general",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "influencer",
    expectedPrimaryNiche: "beauty",
    expectedNiches: ["beauty", "fashion", "lifestyle"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["beauty", "makeup", "lifestyle"],
  },
  {
    id: "golden-fitness-002",
    name: "Trainer Riya",
    platform: "instagram",
    url: "https://www.instagram.com/trainerriya",
    expectedPersonaId: "fitness_gym",
    expectedPersonaName: "Gym",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "established",
    expectedContentStyle: "promotional",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "fitness",
    expectedPrimaryNiche: "fitness",
    expectedNiches: ["fitness", "nutrition", "health"],
    expectedAudience: "fitness",
    minimumConfidence: 0.55,
    tags: ["fitness", "workout", "health"],
  },
  {
    id: "golden-lawyer-001",
    name: "Legal Insights",
    platform: "youtube",
    url: "https://www.youtube.com/@LegalInsights",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "service_based",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.6,
    expectedEntityType: "lawyer",
    expectedPrimaryNiche: "business",
    expectedNiches: ["business", "education"],
    expectedAudience: "professionals",
    minimumConfidence: 0.55,
    tags: ["lawyer", "legal"],
  },
  {
    id: "golden-photographer-002",
    name: "Weddings by Priya",
    platform: "instagram",
    url: "https://www.instagram.com/weddingsbypriya",
    expectedPersonaId: "photography_print_seller",
    expectedPersonaName: "Print Seller",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "professional",
    expectedContentStyle: "inspirational",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.95,
    expectedEntityType: "photographer",
    expectedPrimaryNiche: "photography",
    expectedNiches: ["photography", "travel"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["photographer", "wedding"],
  },
  {
    id: "golden-space-001",
    name: "NASA",
    platform: "youtube",
    url: "https://www.youtube.com/@NASA",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "community",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "strong",
    expectedCommerceStage: "none",
    expectedConfidence: 0.7,
    expectedEntityType: "organization",
    expectedPrimaryNiche: "science",
    expectedNiches: ["science", "technology", "education"],
    expectedAudience: "students",
    minimumConfidence: 0.55,
    tags: ["space", "science", "organization"],
  },
  {
    id: "golden-organization-001",
    name: "TEDx Talks",
    platform: "youtube",
    url: "https://www.youtube.com/@TEDxTalks",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "community",
    expectedCreatorStage: "celebrity",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "strong",
    expectedCommerceStage: "none",
    expectedConfidence: 0.7,
    expectedEntityType: "organization",
    expectedPrimaryNiche: "education",
    expectedNiches: ["education", "science", "business"],
    expectedAudience: "students",
    minimumConfidence: 0.55,
    tags: ["education", "talks", "organization"],
  },
  {
    id: "golden-podcast-001",
    name: "The Growth Show",
    platform: "youtube",
    url: "https://www.youtube.com/@TheGrowthShow",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Lifestyle Creator",
    expectedBusinessModel: "content_monetization",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.75,
    expectedEntityType: "podcast",
    expectedPrimaryNiche: "business",
    expectedNiches: ["business", "marketing"],
    expectedAudience: "professionals",
    minimumConfidence: 0.55,
    tags: ["podcast", "business", "interviews"],
  },
  {
    id: "golden-startup-001",
    name: "Notion Templates Co",
    platform: "instagram",
    url: "https://www.instagram.com/notiontemplatesco",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Developer",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "growing",
    expectedContentStyle: "technical",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "just_started",
    expectedConfidence: 0.7,
    expectedEntityType: "startup",
    expectedPrimaryNiche: "productivity",
    expectedNiches: ["productivity", "technology"],
    expectedAudience: "creators",
    minimumConfidence: 0.55,
    tags: ["startup", "productivity", "templates"],
  },
  {
    id: "golden-food-002",
    name: "Pizza Napoletana",
    platform: "instagram",
    url: "https://www.instagram.com/pizzanapoletana",
    expectedPersonaId: "food_restaurant",
    expectedPersonaName: "Restaurant",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "established",
    expectedContentStyle: "promotional",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.95,
    expectedEntityType: "restaurant",
    expectedPrimaryNiche: "food",
    expectedNiches: ["food", "cooking"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["restaurant", "food", "pizza"],
  },
  {
    id: "golden-food-003",
    name: "Sips Coffee House",
    platform: "instagram",
    url: "https://www.instagram.com/sipscoffeehouse",
    expectedPersonaId: "food_restaurant",
    expectedPersonaName: "Restaurant",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "established",
    expectedContentStyle: "promotional",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.9,
    expectedEntityType: "restaurant",
    expectedPrimaryNiche: "food",
    expectedNiches: ["food", "lifestyle"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["cafe", "food", "coffee"],
  },
  {
    id: "golden-music-002",
    name: "DJ Nova",
    platform: "instagram",
    url: "https://www.instagram.com/djnova",
    expectedPersonaId: "persona-entertainer",
    expectedPersonaName: "Entertainer",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "established",
    expectedContentStyle: "entertainment",
    expectedAudienceType: "general",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.8,
    expectedEntityType: "musician",
    expectedPrimaryNiche: "music",
    expectedNiches: ["music", "dance"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["music", "dj", "dance"],
  },
  {
    id: "golden-education-003",
    name: "Coding Bootcamp Pro",
    platform: "youtube",
    url: "https://www.youtube.com/@CodingBootcampPro",
    expectedPersonaId: "education_course_creator",
    expectedPersonaName: "Course Creator",
    expectedBusinessModel: "education",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "educator",
    expectedPrimaryNiche: "programming",
    expectedNiches: ["programming", "web_development", "education"],
    expectedAudience: "developers",
    minimumConfidence: 0.55,
    tags: ["education", "coding", "bootcamp"],
  },
  {
    id: "golden-fitness-003",
    name: "Yoga with Nia",
    platform: "youtube",
    url: "https://www.youtube.com/@YogaWithNia",
    expectedPersonaId: "fitness_gym",
    expectedPersonaName: "Gym",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "fitness",
    expectedPrimaryNiche: "fitness",
    expectedNiches: ["fitness", "health", "mental_health"],
    expectedAudience: "fitness",
    minimumConfidence: 0.55,
    tags: ["yoga", "fitness", "wellness"],
  },
  {
    id: "golden-fashion-001",
    name: "Street Style Daily",
    platform: "instagram",
    url: "https://www.instagram.com/streetstyledaily",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Lifestyle Creator",
    expectedBusinessModel: "content_monetization",
    expectedCreatorStage: "established",
    expectedContentStyle: "promotional",
    expectedAudienceType: "general",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "influencer",
    expectedPrimaryNiche: "fashion",
    expectedNiches: ["fashion", "lifestyle", "luxury"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["fashion", "style", "influencer"],
  },
  {
    id: "golden-science-001",
    name: "Curious Minds",
    platform: "youtube",
    url: "https://www.youtube.com/@CuriousMinds",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "content_monetization",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.8,
    expectedEntityType: "creator",
    expectedPrimaryNiche: "science",
    expectedNiches: ["science", "education", "technology"],
    expectedAudience: "students",
    minimumConfidence: 0.55,
    tags: ["science", "education"],
  },
  {
    id: "golden-pets-001",
    name: "Pawsome Pets",
    platform: "instagram",
    url: "https://www.instagram.com/pawsomepets",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Lifestyle Creator",
    expectedBusinessModel: "content_monetization",
    expectedCreatorStage: "established",
    expectedContentStyle: "entertainment",
    expectedAudienceType: "general",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.8,
    expectedEntityType: "creator",
    expectedPrimaryNiche: "pets",
    expectedNiches: ["pets", "lifestyle"],
    expectedAudience: "parents",
    minimumConfidence: 0.55,
    tags: ["pets", "animals"],
  },
  {
    id: "golden-automotive-001",
    name: "Car Review Guy",
    platform: "youtube",
    url: "https://www.youtube.com/@CarReviewGuy",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "content_monetization",
    expectedCreatorStage: "established",
    expectedContentStyle: "technical",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.8,
    expectedEntityType: "creator",
    expectedPrimaryNiche: "automotive",
    expectedNiches: ["automotive", "technology"],
    expectedAudience: "professionals",
    minimumConfidence: 0.55,
    tags: ["cars", "automotive", "review"],
  },
  {
    id: "golden-realestate-001",
    name: "Prime Properties",
    platform: "instagram",
    url: "https://www.instagram.com/primeproperties",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "service_based",
    expectedCreatorStage: "established",
    expectedContentStyle: "promotional",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.7,
    expectedEntityType: "company",
    expectedPrimaryNiche: "real_estate",
    expectedNiches: ["real_estate", "business"],
    expectedAudience: "professionals",
    minimumConfidence: 0.55,
    tags: ["real estate", "property"],
  },
  {
    id: "golden-news-001",
    name: "Market Minute",
    platform: "youtube",
    url: "https://www.youtube.com/@MarketMinute",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "content_monetization",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.75,
    expectedEntityType: "creator",
    expectedPrimaryNiche: "news",
    expectedNiches: ["news", "finance"],
    expectedAudience: "professionals",
    minimumConfidence: 0.55,
    tags: ["news", "finance"],
  },
  {
    id: "golden-ai-001",
    name: "AI Whisperer",
    platform: "youtube",
    url: "https://www.youtube.com/@AIWhisperer",
    expectedPersonaId: "tech_developer",
    expectedPersonaName: "Developer",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "professional",
    expectedContentStyle: "technical",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "developer",
    expectedPrimaryNiche: "ai",
    expectedNiches: ["ai", "machine_learning", "technology"],
    expectedAudience: "developers",
    minimumConfidence: 0.55,
    tags: ["ai", "machine learning"],
  },
  {
    id: "golden-consultant-001",
    name: "Brand Strategy Co",
    platform: "instagram",
    url: "https://www.instagram.com/brandstrategyco",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "service_based",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.7,
    expectedEntityType: "consultant",
    expectedPrimaryNiche: "business",
    expectedNiches: ["business", "marketing"],
    expectedAudience: "professionals",
    minimumConfidence: 0.55,
    tags: ["consultant", "branding", "strategy"],
  },
  {
    id: "golden-designer-001",
    name: "Pixel Perfect Studio",
    platform: "instagram",
    url: "https://www.instagram.com/pixelperfectstudio",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "service_based",
    expectedCreatorStage: "professional",
    expectedContentStyle: "inspirational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.75,
    expectedEntityType: "designer",
    expectedPrimaryNiche: "art",
    expectedNiches: ["art", "technology", "productivity"],
    expectedAudience: "professionals",
    minimumConfidence: 0.55,
    tags: ["designer", "ui", "creative"],
  },
  {
    id: "golden-artist-001",
    name: "Canvas & Ink",
    platform: "instagram",
    url: "https://www.instagram.com/canvasandink",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "direct_sales",
    expectedCreatorStage: "established",
    expectedContentStyle: "inspirational",
    expectedAudienceType: "niche",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.8,
    expectedEntityType: "artist",
    expectedPrimaryNiche: "art",
    expectedNiches: ["art", "lifestyle"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["artist", "art", "illustration"],
  },
  {
    id: "golden-marketing-001",
    name: "Growth Marketing Hub",
    platform: "youtube",
    url: "https://www.youtube.com/@GrowthMarketingHub",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "content_monetization",
    expectedCreatorStage: "established",
    expectedContentStyle: "educational",
    expectedAudienceType: "professional",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.8,
    expectedEntityType: "creator",
    expectedPrimaryNiche: "marketing",
    expectedNiches: ["marketing", "business", "finance"],
    expectedAudience: "professionals",
    minimumConfidence: 0.55,
    tags: ["marketing", "growth", "business"],
  },
  {
    id: "golden-comedy-002",
    name: "Standup Central",
    platform: "youtube",
    url: "https://www.youtube.com/@StandupCentral",
    expectedPersonaId: "persona-entertainer",
    expectedPersonaName: "Entertainer",
    expectedBusinessModel: "hybrid",
    expectedCreatorStage: "established",
    expectedContentStyle: "entertainment",
    expectedAudienceType: "general",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "growing",
    expectedConfidence: 0.85,
    expectedEntityType: "creator",
    expectedPrimaryNiche: "comedy",
    expectedNiches: ["comedy", "entertainment"],
    expectedAudience: "beginners",
    minimumConfidence: 0.55,
    tags: ["comedy", "entertainment"],
  },
  {
    id: "golden-ngo-001",
    name: "Green Future",
    platform: "instagram",
    url: "https://www.instagram.com/greenfuture",
    expectedPersonaId: "default_creator",
    expectedPersonaName: "Creator",
    expectedBusinessModel: "community",
    expectedCreatorStage: "established",
    expectedContentStyle: "inspirational",
    expectedAudienceType: "general",
    expectedBrandStrength: "moderate",
    expectedCommerceStage: "none",
    expectedConfidence: 0.7,
    expectedEntityType: "ngo",
    expectedPrimaryNiche: "science",
    expectedNiches: ["science", "health", "organization"],
    expectedAudience: "students",
    minimumConfidence: 0.55,
    tags: ["ngo", "environment", "charity"],
  },
];

export class GoldenDataset {
  private creators: Map<string, GoldenCreatorEntry> = new Map();

  constructor(config?: Partial<GoldenDatasetConfig>) {
    this.config = {
      enabled: true,
      strictMode: false,
      scoreThreshold: 0.7,
      ...config,
    };
    for (const creator of GOLDEN_CREATORS) {
      this.creators.set(creator.id, creator);
    }
  }

  readonly config: GoldenDatasetConfig;

  getCreator(id: string): GoldenCreatorEntry | undefined {
    return this.creators.get(id);
  }

  findByUrl(url: string): GoldenCreatorEntry | undefined {
    const normalized = url.toLowerCase().replace(/\/+$/, "");
    const all = Array.from(this.creators, ([_, v]) => v);
    for (const creator of all) {
      if (creator.url.toLowerCase().replace(/\/+$/, "") === normalized) {
        return creator;
      }
    }
    return undefined;
  }

  findByPlatform(platform: string): GoldenCreatorEntry[] {
    return Array.from(this.creators, ([_, v]) => v).filter(
      (c) => c.platform === platform,
    );
  }

  findByTag(tag: string): GoldenCreatorEntry[] {
    return Array.from(this.creators, ([_, v]) => v).filter((c) =>
      c.tags.includes(tag),
    );
  }

  listAll(): GoldenCreatorEntry[] {
    return Array.from(this.creators, ([_, v]) => v);
  }

  register(entry: GoldenCreatorEntry): void {
    this.creators.set(entry.id, entry);
  }

  isKnownUrl(url: string): boolean {
    return this.findByUrl(url) !== undefined;
  }
}

export const goldenDataset = new GoldenDataset();




