import { componentRegistry } from "./registry";
import type { ComponentDefinition } from "./types";
import {
  HeroRenderer, AboutRenderer, FooterRenderer,
  GalleryRenderer, ProductsRenderer, TimelineRenderer,
  LinksRenderer, TestimonialsRenderer, FaqRenderer,
  ContactRenderer, NewsletterRenderer, PricingRenderer,
  CoursesRenderer, SpotifyRenderer, YouTubeRenderer,
  DiscordRenderer, InstagramRenderer,
} from "./renderers";

const BUILTIN_COMPONENTS: ComponentDefinition[] = [
  // ── Heroes ───────────────────────────────────────────────
  {
    id: "hero.default", type: "hero", name: "Hero", category: "hero",
    icon: "Layout", description: "Full-width hero banner with title, subtitle, and CTA",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }, { id: "slide", name: "Slide Up" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Welcome", subtitle: "", buttonText: "Get Started", buttonLink: "#", alignment: "center" },
    renderer: HeroRenderer,
  },
  {
    id: "hero.gaming", type: "hero", name: "Gaming Hero", category: "hero",
    icon: "Gamepad2", description: "Hero with live badge, stream status, and gaming theme",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Live Now", subtitle: "", showLiveBadge: true },
    renderer: HeroRenderer,
  },
  {
    id: "hero.fitness", type: "hero", name: "Fitness Hero", category: "hero",
    icon: "Dumbbell", description: "Hero with transformation focus and CTA",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Transform Your Body", subtitle: "", cta: "Join Now" },
    renderer: HeroRenderer,
  },
  {
    id: "hero.education", type: "hero", name: "Education Hero", category: "hero",
    icon: "BookOpen", description: "Hero for course creators and educators",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Learn Something New", subtitle: "", cta: "Start Learning" },
    renderer: HeroRenderer,
  },

  // ── About ────────────────────────────────────────────────
  {
    id: "about.default", type: "about", name: "About", category: "about",
    icon: "User", description: "About section with bio, image, and social links",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: true,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "About Me", content: "", imageUrl: "" },
    renderer: AboutRenderer,
  },

  // ── Gallery ──────────────────────────────────────────────
  {
    id: "gallery.grid", type: "gallery", name: "Image Gallery", category: "gallery",
    icon: "Image", description: "Grid layout for images and videos",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: false,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { layout: "grid", columns: 3, images: [] },
    renderer: GalleryRenderer,
  },
  {
    id: "products.grid", type: "products", name: "Products", category: "products",
    icon: "ShoppingBag", description: "Product grid from your store",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { layout: "grid", columns: 3 },
    renderer: ProductsRenderer,
  },
  {
    id: "timeline.default", type: "timeline", name: "Timeline", category: "timeline",
    icon: "Trophy", description: "Career milestones and achievements timeline",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "slide", name: "Slide In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "My Journey" },
    renderer: TimelineRenderer,
  },
  {
    id: "links.default", type: "links", name: "Social Links", category: "links",
    icon: "Link2", description: "Social media and affiliate links",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Connect With Me" },
    renderer: LinksRenderer,
  },
  {
    id: "footer.default", type: "footer", name: "Footer", category: "footer",
    icon: "ArrowDown", description: "Website footer with links and copyright",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { copyright: "© All rights reserved" },
    renderer: FooterRenderer,
  },
  {
    id: "testimonials.default", type: "testimonials", name: "Testimonials", category: "testimonials",
    icon: "MessageSquare", description: "Customer or fan testimonials",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "What People Say" },
    renderer: TestimonialsRenderer,
  },
  {
    id: "faq.default", type: "faq", name: "FAQ", category: "faq",
    icon: "HelpCircle", description: "Frequently asked questions accordion",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: true,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "FAQ", items: [] },
    renderer: FaqRenderer,
  },
  {
    id: "contact.default", type: "contact", name: "Contact", category: "contact",
    icon: "Mail", description: "Contact form section",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Get In Touch", email: "" },
    renderer: ContactRenderer,
  },
  {
    id: "newsletter.default", type: "newsletter", name: "Newsletter", category: "newsletter",
    icon: "Rss", description: "Email newsletter signup form",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Subscribe", placeholder: "Your email" },
    renderer: NewsletterRenderer,
  },
  {
    id: "pricing.default", type: "pricing", name: "Pricing", category: "pricing",
    icon: "CreditCard", description: "Pricing plans and packages",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Plans", plans: [] },
    renderer: PricingRenderer,
  },
  {
    id: "courses.default", type: "courses", name: "Courses", category: "courses",
    icon: "BookOpen", description: "Course catalog for educators",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "My Courses" },
    renderer: CoursesRenderer,
  },
  {
    id: "embed.spotify", type: "embed", name: "Spotify Player", category: "embed",
    icon: "Music", description: "Embedded Spotify music player",
    version: "1.0.0", supportsAI: false, supportsTheme: false, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { url: "", height: "352" },
    renderer: SpotifyRenderer,
  },
  {
    id: "embed.youtube", type: "embed", name: "YouTube Video", category: "embed",
    icon: "Video", description: "Embedded YouTube video player",
    version: "1.0.0", supportsAI: false, supportsTheme: false, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { url: "", autoplay: false },
    renderer: YouTubeRenderer,
  },
  {
    id: "social.discord", type: "social", name: "Discord Widget", category: "social",
    icon: "MessageCircle", description: "Discord community widget",
    version: "1.0.0", supportsAI: false, supportsTheme: false, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { serverId: "", label: "Join Discord" },
    renderer: DiscordRenderer,
  },
  {
    id: "social.instagram", type: "social", name: "Instagram Feed", category: "social",
    icon: "Camera", description: "Instagram photo grid feed",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: false,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { username: "", limit: 6 },
    renderer: InstagramRenderer,
  },
];

export function registerBuiltinComponents(): void {
  for (const comp of BUILTIN_COMPONENTS) {
    componentRegistry.register(comp);
  }
}
