import { componentRegistry } from "./registry";
import type { ComponentDefinition } from "./types";
import type { RegistryFieldDefinition } from "./fields";
import {
  HeroRenderer, HeroSplitRenderer, FooterRenderer,
  GalleryRenderer, GalleryBentoRenderer, ProductsRenderer, TimelineRenderer,
  LinksRenderer, TestimonialsRenderer, TestimonialsMarqueeRenderer, FaqRenderer,
  ContactRenderer, NewsletterRenderer,
  CoursesRenderer, ServicesRenderer, ServicesBentoRenderer, SpotifyRenderer, YouTubeRenderer,
  DiscordRenderer, InstagramRenderer,
  GamesRenderer, ContentFeedRenderer, AffiliateLinksRenderer, BookingsRenderer,
} from "./renderers";

// ── RCCF-VISUAL-02B-01: Puck-style proof — 2 representatives ─
// Fields are serializable (no functions/icons), capability-aware via requiresCapability,
// and single-source for Builder inspector + LayoutEngine defaultProps.
// resolveData is pure (content + config → resolvedData) and keeps the
// PublishedSnapshot → LayoutEngine → renderer path intact.

const PRODUCTS_GRID_FIELDS: RegistryFieldDefinition[] = [
  { name: "columns", label: "Columns", type: "number", group: "layout", defaultValue: 3, validation: { min: 1, max: 6 } },
  { name: "title", label: "Section title", type: "text", group: "content", defaultValue: "", placeholder: "Leave empty for auto-title" },
  { name: "showViewAll", label: "Show View All link", type: "boolean", group: "layout", defaultValue: true },
  // Capability-aware premium field — demonstrates gating via capabilityService (advanced_builder)
  { name: "highlightFeatured", label: "Highlight featured", type: "boolean", group: "layout", defaultValue: false, requiresCapability: "advanced_builder" },
  // Non-persisted toggle for staggered animation control (maps to supportsAnimation)
  { name: "animation", label: "Entrance animation", type: "select", group: "animation", defaultValue: "stagger", options: [{ label: "None", value: "none" }, { label: "Stagger", value: "stagger" }] },
];

const GALLERY_GRID_FIELDS: RegistryFieldDefinition[] = [
  { name: "columns", label: "Columns", type: "number", group: "layout", defaultValue: 3, validation: { min: 1, max: 6 } },
  { name: "layout", label: "Layout style", type: "select", group: "layout", defaultValue: "grid", options: [{ label: "Grid", value: "grid" }, { label: "Masonry", value: "masonry" }] },
  { name: "lightbox", label: "Lightbox", type: "boolean", group: "layout", defaultValue: true },
  // Media-adjacent capability demo — premium gallery density
  { name: "density", label: "Density (premium)", type: "select", group: "layout", defaultValue: "comfortable", options: [{ label: "Comfortable", value: "comfortable" }, { label: "Compact", value: "compact" }], requiresCapability: "advanced_builder" },
];

const BUILTIN_COMPONENTS: ComponentDefinition[] = [
  // ── Heroes ───────────────────────────────────────────────
  {
    id: "hero.default", type: "hero", name: "Hero", category: "hero",
    icon: "Layout", description: "Full-width hero banner with title, subtitle, and CTA",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }, { id: "slide", name: "Slide Up" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Welcome", subtitle: "", buttonText: "Get Started", buttonLink: "#", alignment: "center" },
    renderer: HeroRenderer,
  },
  {
    id: "hero.gaming", type: "hero", name: "Gaming Hero", category: "hero",
    icon: "Gamepad2", description: "Hero with live badge, stream status, and gaming theme",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Live Now", subtitle: "", showLiveBadge: true },
    renderer: HeroRenderer,
  },
  {
    id: "hero.fitness", type: "hero", name: "Fitness Hero", category: "hero",
    icon: "Dumbbell", description: "Hero with transformation focus and CTA",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Transform Your Body", subtitle: "", cta: "Join Now" },
    renderer: HeroRenderer,
  },
  {
    id: "hero.education", type: "hero", name: "Education Hero", category: "hero",
    icon: "BookOpen", description: "Hero for course creators and educators",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Learn Something New", subtitle: "", cta: "Start Learning" },
    renderer: HeroRenderer,
  },
  {
    id: "hero.split", type: "hero", name: "Hero Split", category: "hero",
    icon: "Columns2", description: "60/40 split hero — text + media side-by-side with stats/trust row",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Welcome", subtitle: "", cta: "Get Started", ctaLink: "#", showStats: true },
    renderer: HeroSplitRenderer,
  },

  // ── Gallery ──────────────────────────────────────────────
  {
    id: "gallery.grid", type: "gallery", name: "Image Gallery", category: "gallery",
    icon: "Image", description: "Grid layout for images and videos",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: false,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { layout: "grid", columns: 3, lightbox: true, density: "comfortable" },
    // RCCF-VISUAL-02B-01: fields + resolveData proof — same contract drives Builder + rendering
    fields: GALLERY_GRID_FIELDS,
    resolveData: ({ content }) => {
      const imageEntries = content.gallery.map((g) => ({
        id: g.id,
        url: g.imageUrl,
        caption: g.title || g.description || "",
        description: g.description,
        videoUrl: g.videoUrl,
        altText: g.altText,
        isVideo: g.mediaType === "video",
      }));
      return { resolvedData: imageEntries, resolvedTitle: "Gallery" };
    },
    renderer: GalleryRenderer,
  },
  {
    id: "gallery.bento", type: "gallery", name: "Gallery Bento", category: "gallery",
    icon: "LayoutGrid", description: "Asymmetric bento — featured image + supporting tiles",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: false,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { layout: "bento", images: [] },
    renderer: GalleryBentoRenderer,
  },
  {
    id: "products.grid", type: "products", name: "Products", category: "products",
    icon: "ShoppingBag", description: "Product grid from your store",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { layout: "grid", columns: 3, title: "", showViewAll: true, highlightFeatured: false, animation: "stagger" },
    // RCCF-VISUAL-02B-01: fields + resolveData proof
    fields: PRODUCTS_GRID_FIELDS,
    resolveData: ({ content }) => {
      const productEntries = content.products.map((p) => ({
        id: p.id,
        name: p.name,
        description: p.description,
        price: p.price,
        imageUrl: p.imageUrl,
        slug: p.slug,
        isFeatured: p.isFeatured,
        commerceMode: p.commerceMode,
        whatsappUrl: p.whatsappUrl,
      }));
      const resolvedTitle = content.identity.name ? `${content.identity.name}'s Products` : "Products";
      return { resolvedData: productEntries, resolvedTitle };
    },
    renderer: ProductsRenderer,
  },
  {
    id: "timeline.default", type: "timeline", name: "Timeline", category: "timeline",
    icon: "Trophy", description: "Career milestones and achievements timeline",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "slide", name: "Slide In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "My Journey" },
    renderer: TimelineRenderer,
  },
  {
    id: "links.default", type: "links", name: "Social Links", category: "links",
    icon: "Link2", description: "Social media and affiliate links",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Connect With Me" },
    renderer: LinksRenderer,
  },
  {
    id: "affiliateLinks.default", type: "affiliateLinks", name: "Affiliate Links", category: "links",
    icon: "Link2", description: "Affiliate product links with click tracking",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Affiliate Links" },
    renderer: AffiliateLinksRenderer,
  },
  {
    id: "footer.default", type: "footer", name: "Footer", category: "footer",
    icon: "ArrowDown", description: "Website footer with links and copyright",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { copyright: "© All rights reserved" },
    renderer: FooterRenderer,
  },
  {
    id: "testimonials.default", type: "testimonials", name: "Testimonials", category: "testimonials",
    icon: "MessageSquare", description: "Customer or fan testimonials",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "fade", name: "Fade In" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "What People Say" },
    renderer: TestimonialsRenderer,
  },
  {
    id: "testimonials.marquee", type: "testimonials", name: "Testimonials Marquee", category: "testimonials",
    icon: "GalleryHorizontal", description: "Horizontal marquee — auto-scroll, pause on hover, motion-gated",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: false,
    animations: [{ id: "marquee", name: "Marquee" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "What People Say", speed: "normal" },
    renderer: TestimonialsMarqueeRenderer,
  },
  {
    id: "faq.default", type: "faq", name: "FAQ", category: "faq",
    icon: "HelpCircle", description: "Frequently asked questions accordion",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: true,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "FAQ", items: [] },
    renderer: FaqRenderer,
  },
  {
    id: "contact.default", type: "contact", name: "Contact", category: "contact",
    icon: "Mail", description: "Contact form section",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Get In Touch", email: "" },
    renderer: ContactRenderer,
  },
  {
    id: "newsletter.default", type: "newsletter", name: "Newsletter", category: "newsletter",
    icon: "Rss", description: "Email newsletter signup form",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Subscribe", placeholder: "Your email" },
    renderer: NewsletterRenderer,
  },
  {
    id: "courses.default", type: "courses", name: "Courses", category: "courses",
    icon: "BookOpen", description: "Course catalog for educators",
    version: "1.0.0", supportsAI: true, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: true,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "My Courses" },
    renderer: CoursesRenderer,
  },
  {
    id: "services.default", type: "services", name: "Services", category: "services",
    icon: "Briefcase", description: "Services and coaching packages",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Services" },
    renderer: ServicesRenderer,
  },
  {
    id: "services.bento", type: "services", name: "Services Bento", category: "services",
    icon: "LayoutGrid", description: "Bento — 1 featured + supporting cards",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: false,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Services" },
    renderer: ServicesBentoRenderer,
  },
  {
    id: "bookings.default", type: "bookings", name: "Bookings", category: "bookings",
    icon: "CalendarDays", description: "Book a session or appointment",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Book a Session" },
    renderer: BookingsRenderer,
  },
  {
    id: "embed.spotify", type: "embed", name: "Spotify Player", category: "embed",
    icon: "Music", description: "Embedded Spotify music player",
    version: "1.0.0", supportsAI: false, supportsTheme: false, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { url: "", height: "352" },
    renderer: SpotifyRenderer,
  },
  {
    id: "embed.youtube", type: "embed", name: "YouTube Video", category: "embed",
    icon: "Video", description: "Embedded YouTube video player",
    version: "1.0.0", supportsAI: false, supportsTheme: false, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { url: "", autoplay: false },
    renderer: YouTubeRenderer,
  },
  {
    id: "social.discord", type: "social", name: "Discord Widget", category: "social",
    icon: "MessageCircle", description: "Discord community widget",
    version: "1.0.0", supportsAI: false, supportsTheme: false, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { serverId: "", label: "Join Discord" },
    renderer: DiscordRenderer,
  },
  {
    id: "games.default", type: "games", name: "Games", category: "games",
    icon: "Gamepad2", description: "Games and gaming content",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Games" },
    renderer: GamesRenderer,
  },
  {
    id: "contentFeed.default", type: "contentFeed", name: "Content Feed", category: "contentFeed",
    icon: "Rss", description: "Social content feed grid",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: false,
    supportsResponsive: true, supportsSEO: false,
    animations: [], responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { title: "Latest Content" },
    renderer: ContentFeedRenderer,
  },
  {
    id: "social.instagram", type: "social", name: "Instagram Feed", category: "social",
    icon: "Camera", description: "Instagram photo grid feed",
    version: "1.0.0", supportsAI: false, supportsTheme: true, supportsAnimation: true,
    supportsResponsive: true, supportsSEO: false,
    animations: [{ id: "stagger", name: "Stagger" }],
    responsive: { mobile: true, tablet: true, desktop: true },
    validation: { schema: {} },
    defaultProps: { username: "", limit: 6 },
    renderer: InstagramRenderer,
  },
];

export function registerBuiltinComponents(): void {
  for (const comp of BUILTIN_COMPONENTS) {
    componentRegistry.register(comp);
  }
}
