import type { TrustCTA } from "./types";

export const SEED_CTAS: TrustCTA[] = [
  {
    id: "creator-start-free",
    label: "Generate My Storefront — Free",
    href: "/signup",
    variant: "primary",
    audience: "creator",
    description: "Paste your profile URL and get a complete storefront in under 2 minutes.",
  },
  {
    id: "creator-try-builder",
    label: "Try the Builder",
    href: "/signup",
    variant: "secondary",
    audience: "creator",
    description: "Experience the drag-and-drop builder with your own content.",
  },
  {
    id: "creator-view-pricing",
    label: "View Plans",
    href: "/pricing",
    variant: "ghost",
    audience: "creator",
    description: "Compare features and find the right plan for your business.",
  },
  {
    id: "agency-start-free",
    label: "Start Your Agency — Free",
    href: "/signup?plan=agency",
    variant: "primary",
    audience: "agency",
    description: "Multi-client workspaces, white-label, and centralized billing.",
  },
  {
    id: "agency-view-features",
    label: "Agency Features",
    href: "/features#agency",
    variant: "secondary",
    audience: "agency",
    description: "Explore team collaboration, revenue splitting, and more.",
  },
  {
    id: "enterprise-contact",
    label: "Contact Sales",
    href: "/contact",
    variant: "primary",
    audience: "enterprise",
    description: "Custom pricing, dedicated support, and SLAs for large teams.",
  },
  {
    id: "enterprise-demo",
    label: "Request a Demo",
    href: "/contact",
    variant: "secondary",
    audience: "enterprise",
    description: "See CreatorStore in action with a personalized walkthrough.",
  },
  {
    id: "demo-watch",
    label: "Watch the Demo",
    href: "/#ai-demo",
    variant: "secondary",
    audience: "general",
    description: "See how a complete storefront is built from a profile URL.",
  },
  {
    id: "general-signup",
    label: "Get Started Free",
    href: "/signup",
    variant: "primary",
    audience: "general",
    description: "No credit card required. 2-minute setup.",
  },
  {
    id: "general-contact",
    label: "Contact Us",
    href: "/contact",
    variant: "ghost",
    audience: "general",
    description: "Have questions? We're here to help.",
  },
  {
    id: "general-learn-more",
    label: "Learn More",
    href: "/features",
    variant: "secondary",
    audience: "general",
    description: "Explore all CreatorStore features and capabilities.",
  },
];
