import type { DemoSeed } from "./types";

export const SEED_VERSION = "1.0";
export const GENERATOR_VERSION = "1.0";

const p = (name: string, price: number, desc: string) => ({ name, price, description: desc });
const t = (name: string, text: string) => ({ name, text });
const f = (q: string, a: string) => ({ q, a });

export const DEMO_SEEDS: DemoSeed[] = [
  {
    id: "fitness-coach", industry: "Fitness Coach", persona: "Coach",
    audience: "Fitness enthusiasts, beginners",
    brand: { name: "FitLife Pro", tagline: "Transform Your Body", voice: "Motivational, energetic",
      palette: { primary: "#EF4444", secondary: "#F97316" } },
    content: { bio: "Certified personal trainer with 8+ years transforming lives.", hero: "Your Best Body Starts Here.", about: "Science-backed programs for real results.", seoTitle: "Fitness Coach | Personal Training", seoDesc: "Personal training and nutrition coaching." },
    products: [ p("12-Week Program", 2999, "Complete transformation plan"), p("Meal Plan", 999, "Custom nutrition guide"), p("1-on-1 Coaching", 4999, "Weekly sessions") ],
    testimonials: [ t("Rahul M.", "Lost 12kg in 3 months!"), t("Priya S.", "Best investment in my health") ],
    faq: [ f("Do I need equipment?", "Basic equipment recommended."), f("Is it suitable for beginners?", "Yes, all levels welcome.") ],
    pages: ["hero", "about", "products", "testimonials", "faq", "contact"],
  },
  {
    id: "yoga-studio", industry: "Yoga Studio", persona: "Instructor",
    audience: "Wellness seekers, beginners",
    brand: { name: "ZenFlow Yoga", tagline: "Find Your Inner Peace", voice: "Calm, mindful",
      palette: { primary: "#8B5CF6", secondary: "#06B6D4" } },
    content: { bio: "Certified yoga instructor creating a welcoming community.", hero: "Breathe. Move. Transform.", about: "Classes for all levels. Online and in-person.", seoTitle: "Yoga Studio | Online Classes", seoDesc: "Join our yoga community." },
    products: [ p("Monthly Unlimited", 1999, "All classes access"), p("21-Day Challenge", 999, "Daily sessions"), p("Meditation Course", 799, "Stress relief") ],
    testimonials: [ t("Anjali K.", "Found peace and flexibility."), t("Vikram R.", "Life-changing practice") ],
    faq: [ f("Do I need a mat?", "Yes, any yoga mat works."), f("Can I join mid-month?", "Absolutely, pro-rated.") ],
    pages: ["hero", "about", "classes", "testimonials", "faq"],
  },
  {
    id: "photographer", industry: "Photographer", persona: "Creative",
    audience: "Couples, families, businesses",
    brand: { name: "Aperture Art", tagline: "Moments That Last", voice: "Artistic, editorial",
      palette: { primary: "#18181B", secondary: "#71717A" } },
    content: { bio: "Award-winning photographer specializing in weddings and portraits.", hero: "Every Frame Tells a Story.", about: "Cinematic photography for your most important moments.", seoTitle: "Photographer | Wedding & Portrait", seoDesc: "Professional photography services." },
    products: [ p("Wedding Package", 49999, "Full-day coverage"), p("Portrait Session", 4999, "1-hour, 20 edits"), p("Preset Pack", 1499, "25 Lightroom presets") ],
    testimonials: [ t("Neha & Arjun", "Our wedding photos are magical."), t("Rohit G.", "Professional and creative") ],
    faq: [ f("How many photos do I get?", "500+ edited images."), f("Do you travel?", "Yes, pan-India.") ],
    pages: ["hero", "portfolio", "about", "testimonials", "contact"],
  },
  {
    id: "fashion-brand", industry: "Fashion Brand", persona: "Creator",
    audience: "Young professionals, fashion-forward",
    brand: { name: "Urban Vogue", tagline: "Wear Your Confidence", voice: "Bold, stylish",
      palette: { primary: "#D946EF", secondary: "#FB923C" } },
    content: { bio: "Contemporary fashion for the modern individual.", hero: "Style Without Compromise.", about: "Premium materials. Bold designs.", seoTitle: "Fashion Brand | Premium Apparel", seoDesc: "Contemporary fashion for modern individuals." },
    products: [ p("Signature Tee", 1499, "Premium cotton"), p("Limited Jacket", 4999, "Handcrafted"), p("Accessories Bundle", 2499, "Curated set") ],
    testimonials: [ t("Meera L.", "My go-to brand now."), t("Karan D.", "Quality is unmatched") ],
    faq: [ f("What sizes are available?", "XS to XXL."), f("Do you ship internationally?", "Yes, worldwide.") ],
    pages: ["hero", "collection", "about", "testimonials", "faq"],
  },
  {
    id: "digital-agency", industry: "Digital Agency", persona: "Agency",
    audience: "Startups, SMEs, enterprises",
    brand: { name: "Nexus Digital", tagline: "Digital Growth, Delivered", voice: "Professional, innovative",
      palette: { primary: "#6366F1", secondary: "#8B5CF6" } },
    content: { bio: "Full-service agency helping brands grow through design and development.", hero: "We Build Digital Experiences That Convert.", about: "From startups to enterprises, we deliver results.", seoTitle: "Digital Agency | Design & Development", seoDesc: "Full-service digital agency." },
    products: [ p("Website Package", 49999, "5 pages, responsive"), p("SEO Audit", 14999, "Comprehensive analysis"), p("Social Media", 9999, "Monthly management") ],
    testimonials: [ t("TechStart Inc.", "3x conversion increase."), t("GreenEarth NGO", "Professional and fast") ],
    faq: [ f("What's your process?", "Discovery → Design → Build → Launch."), f("Do you offer maintenance?", "Yes, monthly retainers.") ],
    pages: ["hero", "services", "portfolio", "testimonials", "contact"],
  },
  {
    id: "finance-educator", industry: "Finance Educator", persona: "Creator",
    audience: "Young investors, professionals",
    brand: { name: "MarketWise", tagline: "Invest Smarter", voice: "Educational, trustworthy",
      palette: { primary: "#059669", secondary: "#3B82F6" } },
    content: { bio: "Making finance simple for everyone.", hero: "Master Your Money.", about: "Practical investing education for the Indian market.", seoTitle: "Finance Educator | Investing Courses", seoDesc: "Learn investing from an experienced educator." },
    products: [ p("Stock Market Course", 4999, "Complete beginner-to-pro"), p("Option Trading Mastery", 7999, "Advanced strategies"), p("Investment Toolkit", 999, "Templates & calculators") ],
    testimonials: [ t("Amit P.", "Finally understand markets."), t("Sneha R.", "My portfolio is up 40%") ],
    faq: [ f("Do I need prior knowledge?", "No, starts from basics."), f("Is this for Indian markets?", "Yes, NSE/BSE focused.") ],
    pages: ["hero", "courses", "about", "testimonials", "faq"],
  },
  {
    id: "restaurant-chef", industry: "Restaurant / Chef", persona: "Creator",
    audience: "Food lovers, home cooks",
    brand: { name: "Spice & Soul", tagline: "Taste the Tradition", voice: "Warm, inviting",
      palette: { primary: "#EA580C", secondary: "#F59E0B" } },
    content: { bio: "Award-winning chef bringing authentic flavors to your table.", hero: "Where Every Meal Tells a Story.", about: "Traditional recipes with a modern twist. Fresh ingredients, bold flavors.", seoTitle: "Chef | Cooking Classes & Recipes", seoDesc: "Authentic cooking classes and recipes." },
    products: [ p("Cooking Masterclass", 2999, "20+ recipe video course"), p("Recipe eBook", 599, "50 signature recipes"), p("Spice Kit", 1499, "Premium spices delivered") ],
    testimonials: [ t("Deepa M.", "My family loves the recipes!"), t("Vikram S.", "Finally cooking like a pro") ],
    faq: [ f("Are ingredients easy to find?", "Yes, all locally available."), f("Do you offer vegetarian options?", "Full vegetarian section.") ],
    pages: ["hero", "menu", "about", "testimonials", "faq"],
  },
  {
    id: "dentist-clinic", industry: "Dentist / Clinic", persona: "Professional",
    audience: "Patients, families",
    brand: { name: "SmileCare Dental", tagline: "Your Smile, Our Priority", voice: "Professional, reassuring",
      palette: { primary: "#2563EB", secondary: "#06B6D4" } },
    content: { bio: "State-of-the-art dental care with a gentle touch.", hero: "Confidence Starts With Your Smile.", about: "Advanced dental treatments in a comfortable environment.", seoTitle: "Dental Clinic | Cosmetic & General Dentistry", seoDesc: "Professional dental care for the whole family." },
    products: [ p("Teeth Whitening", 4999, "Professional whitening"), p("Dental Checkup", 999, "Complete examination"), p("Invisalign Consultation", 1999, "Clear aligner assessment") ],
    testimonials: [ t("Ravi K.", "Painless treatment!"), t("Sunita P.", "Best dentist in the area") ],
    faq: [ f("Do you accept insurance?", "Yes, all major providers."), f("Is parking available?", "Free parking on-site.") ],
    pages: ["hero", "services", "about", "testimonials", "faq", "contact"],
  },
  {
    id: "lawyer-legal", industry: "Lawyer / Legal", persona: "Professional",
    audience: "Individuals, businesses",
    brand: { name: "LexGuard Legal", tagline: "Justice. Delivered.", voice: "Authoritative, trustworthy",
      palette: { primary: "#1E3A5F", secondary: "#D97706" } },
    content: { bio: "Experienced legal counsel for individuals and businesses.", hero: "Your Rights. Our Mission.", about: "15+ years of legal expertise across corporate, civil, and family law.", seoTitle: "Law Firm | Legal Services", seoDesc: "Experienced legal counsel for all matters." },
    products: [ p("Legal Consultation", 2499, "1-hour session"), p("Document Review", 4999, "Contract analysis"), p("Representation Package", 14999, "Full case handling") ],
    testimonials: [ t("Arun G.", "Won my case in record time."), t("Lakshmi N.", "Professional and thorough") ],
    faq: [ f("Do you offer free consultation?", "First 15 minutes free."), f("What areas do you cover?", "Corporate, civil, family law.") ],
    pages: ["hero", "services", "about", "testimonials", "faq", "contact"],
  },
  {
    id: "architect-firm", industry: "Architect / Firm", persona: "Professional",
    audience: "Homeowners, developers",
    brand: { name: "Forma Architects", tagline: "Design That Inspires", voice: "Creative, precise",
      palette: { primary: "#374151", secondary: "#F59E0B" } },
    content: { bio: "Award-winning architecture firm creating spaces that inspire.", hero: "Where Vision Meets Structure.", about: "Sustainable, innovative design for residential and commercial projects.", seoTitle: "Architecture Firm | Design & Planning", seoDesc: "Award-winning architectural design services." },
    products: [ p("Home Design Package", 99999, "Complete home design"), p("Renovation Plan", 49999, "Remodel consultation"), p("3D Visualization", 14999, "Photorealistic renders") ],
    testimonials: [ t("The Sharma Family", "Our dream home, realized."), t("BuildCorp Ltd.", "Exceptional work") ],
    faq: [ f("Do you handle permits?", "Yes, end-to-end."), f("What's your design process?", "Consult → Concept → Detailed → Build.") ],
    pages: ["hero", "portfolio", "services", "testimonials", "faq"],
  },
  {
    id: "real-estate-consultant", industry: "Real Estate", persona: "Professional",
    audience: "Buyers, sellers, investors",
    brand: { name: "PrimeEdge Realty", tagline: "Find Your Place", voice: "Trustworthy, knowledgeable",
      palette: { primary: "#0F766E", secondary: "#F59E0B" } },
    content: { bio: "Helping families find their perfect home for over a decade.", hero: "Your Dream Home Awaits.", about: "Expert guidance for buying, selling, and investing in real estate.", seoTitle: "Real Estate Consultant | Property Services", seoDesc: "Expert real estate guidance." },
    products: [ p("Property Valuation", 4999, "Detailed market analysis"), p("Buyer's Guide", 999, "Complete home-buying toolkit"), p("Investment Consult", 9999, "Portfolio strategy") ],
    testimonials: [ t("The Iyer Family", "Found our home in 2 weeks."), t("Rajat M.", "Best investment decision ever") ],
    faq: [ f("Do you cover all areas?", "Pan-India coverage."), f("What's the buying process?", "Search → Visit → Negotiate → Close.") ],
    pages: ["hero", "listings", "about", "testimonials", "faq"],
  },
  {
    id: "music-teacher", industry: "Music Teacher", persona: "Creator",
    audience: "Students, hobbyists, aspiring musicians",
    brand: { name: "Harmony Studio", tagline: "Discover Your Sound", voice: "Passionate, encouraging",
      palette: { primary: "#7C3AED", secondary: "#EC4899" } },
    content: { bio: "Professional musician offering lessons for all ages and skill levels.", hero: "Music Is For Everyone.", about: "Learn guitar, piano, or vocals from a working musician with 12 years of teaching experience.", seoTitle: "Music Teacher | Online & In-Person Lessons", seoDesc: "Professional music lessons for all ages." },
    products: [ p("Beginner Guitar Course", 1999, "12-week structured course"), p("Piano Fundamentals", 2499, "Learn to read and play"), p("Vocal Training", 1499, "Find your voice") ],
    testimonials: [ t("Aditya K.", "Playing my first song in 2 months!"), t("Maya S.", "Patient and talented teacher") ],
    faq: [ f("Do I need my own instrument?", "Yes, any basic instrument works."), f("What ages do you teach?", "6 to 60+.") ],
    pages: ["hero", "courses", "about", "testimonials", "faq"],
  },
  {
    id: "travel-creator", industry: "Travel Creator", persona: "Creator",
    audience: "Travelers, backpackers, explorers",
    brand: { name: "WanderLens", tagline: "Explore More", voice: "Adventurous, inspiring",
      palette: { primary: "#0284C7", secondary: "#0EA5E9" } },
    content: { bio: "Full-time traveler sharing guides, tips, and stories from 40+ countries.", hero: "The World Is Waiting.", about: "From budget backpacking to luxury escapes — honest travel content that helps you travel better.", seoTitle: "Travel Creator | Guides & Inspiration", seoDesc: "Travel guides and inspiration from 40+ countries." },
    products: [ p("Travel Planning Service", 2999, "Personalized itinerary"), p("Packing Guide eBook", 599, "Ultimate packing checklist"), p("Preset Pack", 999, "Travel photo presets") ],
    testimonials: [ t("Rohan D.", "Planned my entire Europe trip!"), t("Kavita L.", "Authentic and useful content") ],
    faq: [ f("Do you plan group trips?", "Yes, twice a year."), f("What's your favorite country?", "Japan, hands down.") ],
    pages: ["hero", "destinations", "about", "testimonials", "faq"],
  },
  {
    id: "interior-designer", industry: "Interior Designer", persona: "Creative",
    audience: "Homeowners, offices, commercial",
    brand: { name: "Muse Interiors", tagline: "Spaces That Speak", voice: "Elegant, thoughtful",
      palette: { primary: "#78350F", secondary: "#D97706" } },
    content: { bio: "Creating beautiful, functional spaces that reflect your personality.", hero: "Design Your Life.", about: "Award-winning interior design studio specializing in residential and commercial projects.", seoTitle: "Interior Designer | Residential & Commercial", seoDesc: "Award-winning interior design services." },
    products: [ p("Room Design Package", 29999, "Single room complete design"), p("Full Home Makeover", 99999, "Complete home redesign"), p("Design Consultation", 4999, "Expert advice session") ],
    testimonials: [ t("The Kapoors", "Our home looks like a magazine!"), t("OfficeHub Co.", "Productivity increased 30%") ],
    faq: [ f("Do you work within budget?", "Yes, we design for all budgets."), f("How long does a project take?", "2-8 weeks depending on scope.") ],
    pages: ["hero", "portfolio", "services", "testimonials", "faq"],
  },
  {
    id: "marketing-consultant", industry: "Marketing Consultant", persona: "Agency",
    audience: "Businesses, startups, brands",
    brand: { name: "GrowthPilot", tagline: "Data-Driven Growth", voice: "Strategic, analytical",
      palette: { primary: "#4F46E5", secondary: "#06B6D4" } },
    content: { bio: "Helping businesses scale through strategic marketing and data-driven decisions.", hero: "Grow Smarter. Not Harder.", about: "From startups to enterprises — marketing strategies that deliver measurable ROI.", seoTitle: "Marketing Consultant | Growth Strategy", seoDesc: "Data-driven marketing strategies for growth." },
    products: [ p("Marketing Audit", 14999, "Complete strategy review"), p("Growth Playbook", 29999, "Custom 90-day plan"), p("Monthly Retainer", 49999, "Ongoing strategy & execution") ],
    testimonials: [ t("SaaSFlow Inc.", "3x lead generation in Q1."), t("EcoShop Co.", "Our best marketing investment") ],
    faq: [ f("What industries do you serve?", "SaaS, e-commerce, services."), f("How do you measure success?", "Revenue lift, CAC reduction, LTV.") ],
    pages: ["hero", "services", "case-studies", "testimonials", "faq"],
  },
  {
    id: "event-planner", industry: "Event Planner", persona: "Creative",
    audience: "Couples, corporates, families",
    brand: { name: "CelebrateCo", tagline: "Moments Made Magical", voice: "Warm, organized",
      palette: { primary: "#BE185D", secondary: "#F59E0B" } },
    content: { bio: "Creating unforgettable events with meticulous planning and creative flair.", hero: "Your Event. Perfected.", about: "From intimate gatherings to grand celebrations — we handle every detail so you can enjoy the moment.", seoTitle: "Event Planner | Weddings & Corporate Events", seoDesc: "Professional event planning for all occasions." },
    products: [ p("Wedding Planning", 99999, "Full-service wedding planning"), p("Corporate Event", 49999, "Conference & gala management"), p("Birthday Package", 19999, "Complete party planning") ],
    testimonials: [ t("Neha & Vikram", "Our wedding was perfect!"), t("TechConf India", "Flawless execution") ],
    faq: [ f("How far in advance should I book?", "3-6 months ideally."), f("Do you handle vendor management?", "Yes, end-to-end.") ],
    pages: ["hero", "services", "gallery", "testimonials", "faq"],
  },
  {
    id: "chartered-accountant", industry: "CA / Accountant", persona: "Professional",
    audience: "Businesses, individuals, startups",
    brand: { name: "TaxWise CA", tagline: "Your Finances. Simplified.", voice: "Precise, reliable",
      palette: { primary: "#1E3A5F", secondary: "#10B981" } },
    content: { bio: "Trusted chartered accountant helping businesses stay compliant and grow.", hero: "Financial Clarity For Your Business.", about: "GST, income tax, audit, and advisory — all under one roof.", seoTitle: "Chartered Accountant | Tax & Audit Services", seoDesc: "Professional CA services for businesses." },
    products: [ p("GST Filing (Monthly)", 1999, "Complete GST compliance"), p("ITR Filing", 1499, "Income tax return"), p("Business Audit", 14999, "Annual audit package") ],
    testimonials: [ t("StartupZen", "Saved us lakhs in taxes."), t("RetailMart Ltd.", "Reliable and professional") ],
    faq: [ f("Do you handle notices?", "Yes, full representation."), f("What's included in GST filing?", "Return filing + reconciliation.") ],
    pages: ["hero", "services", "about", "testimonials", "faq"],
  },
  {
    id: "artist-painter", industry: "Artist / Painter", persona: "Creative",
    audience: "Art collectors, enthusiasts, decor",
    brand: { name: "Canvas & Hue", tagline: "Art That Speaks", voice: "Expressive, authentic",
      palette: { primary: "#92400E", secondary: "#DC2626" } },
    content: { bio: "Contemporary artist creating vibrant paintings that bring spaces to life.", hero: "Color Your World.", about: "Original artworks and commissioned pieces. Each painting tells a unique story.", seoTitle: "Artist | Original Paintings & Commissions", seoDesc: "Contemporary original paintings and commissions." },
    products: [ p("Original Canvas (Medium)", 14999, "24x36 original painting"), p("Commissioned Portrait", 24999, "Custom portrait"), p("Art Print Set", 2999, "3 high-quality prints") ],
    testimonials: [ t("Ananya R.", "The centerpiece of my living room."), t("GalleryNine", "Consistently outstanding work") ],
    faq: [ f("Do you ship internationally?", "Yes, worldwide shipping."), f("Can I visit your studio?", "By appointment.") ],
    pages: ["hero", "gallery", "about", "testimonials", "faq"],
  },
  {
    id: "nutrition-coach", industry: "Nutrition Coach", persona: "Coach",
    audience: "Health-conscious, weight management",
    brand: { name: "NutriPath", tagline: "Nourish Your Best Self", voice: "Scientific, supportive",
      palette: { primary: "#16A34A", secondary: "#F59E0B" } },
    content: { bio: "Clinical nutritionist helping people achieve their health goals through food.", hero: "Eat Well. Live Better.", about: "Evidence-based nutrition plans tailored to your body, lifestyle, and goals.", seoTitle: "Nutrition Coach | Diet Plans & Consultation", seoDesc: "Personalized nutrition plans and coaching." },
    products: [ p("Personalized Diet Plan", 1999, "30-day custom plan"), p("Gut Health Program", 2999, "6-week protocol"), p("Nutrition Consultation", 999, "1-hour session") ],
    testimonials: [ t("Rohini K.", "Lost 8kg without starving!"), t("Manish T.", "My energy levels are through the roof") ],
    faq: [ f("Do you prescribe supplements?", "Food-first approach."), f("Is this suitable for diabetics?", "Yes, specialized plans available.") ],
    pages: ["hero", "programs", "about", "testimonials", "faq"],
  },
  {
    id: "language-academy", industry: "Language Academy", persona: "Creator",
    audience: "Students, professionals, travelers",
    brand: { name: "LinguaHub", tagline: "Speak The World", voice: "Supportive, structured",
      palette: { primary: "#7C3AED", secondary: "#06B6D4" } },
    content: { bio: "Learn languages from native speakers with immersive, practical methods.", hero: "Unlock New Worlds.", about: "Spanish, French, German, Japanese — choose your language and start speaking from day one.", seoTitle: "Language Academy | Online Language Courses", seoDesc: "Learn languages online with native speakers." },
    products: [ p("Beginner Course (3 Months)", 4999, "Structured language course"), p("Conversation Practice", 1999, "10 live sessions"), p("Exam Prep (IELTS/DELE)", 7999, "Full preparation course") ],
    testimonials: [ t("Shweta P.", "Speaking Spanish confidently now!"), t("Arun K.", "Cleared B1 in 4 months") ],
    faq: [ f("What languages do you offer?", "Spanish, French, German, Japanese."), f("Are classes live or recorded?", "Both options available.") ],
    pages: ["hero", "courses", "about", "testimonials", "faq"],
  },
  {
    id: "jewelry-store", industry: "Jewelry Store", persona: "Creator",
    audience: "Jewelry lovers, gift shoppers",
    brand: { name: "Aurelia Jewels", tagline: "Crafted to Shine", voice: "Elegant, luxurious",
      palette: { primary: "#D97706", secondary: "#92400E" } },
    content: { bio: "Handcrafted jewelry that celebrates life's special moments.", hero: "Timeless Elegance.", about: "Each piece is designed and crafted with precision. From everyday essentials to statement pieces.", seoTitle: "Jewelry Store | Handcrafted Fine Jewelry", seoDesc: "Handcrafted jewelry for every occasion." },
    products: [ p("Gold Plated Necklace", 2999, "Delicate chain with pendant"), p("Silver Earring Set", 1999, "Set of 3 pairs"), p("Custom Name Bracelet", 1499, "Personalized jewelry") ],
    testimonials: [ t("Priya M.", "Gorgeous packaging and quality."), t("Rajat S.", "Perfect anniversary gift") ],
    faq: [ f("Is it real gold?", "Gold-plated over sterling silver."), f("Do you offer gift wrapping?", "Yes, complimentary.") ],
    pages: ["hero", "collection", "about", "testimonials", "faq"],
  },
  {
    id: "ngo-charity", industry: "NGO / Charity", persona: "Organization",
    audience: "Donors, volunteers, community",
    brand: { name: "HopeBridge Foundation", tagline: "Together We Rise", voice: "Compassionate, inspiring",
      palette: { primary: "#166534", secondary: "#F59E0B" } },
    content: { bio: "Non-profit organization dedicated to education and healthcare for underprivileged communities.", hero: "Change A Life Today.", about: "Over 10,000 children educated and 50,000 families supported through healthcare initiatives.", seoTitle: "NGO | Education & Healthcare Charity", seoDesc: "Support education and healthcare for underprivileged communities." },
    products: [ p("Sponsor a Child", 999, "Monthly education sponsorship"), p("Medical Camp Donation", 4999, "Fund a health camp"), p("School Supplies Kit", 1499, "One child's annual supplies") ],
    testimonials: [ t("Volunteer Amit", "Seeing those smiles changed me."), t("Donor Meera", "Transparent and impactful") ],
    faq: [ f("Is my donation tax-deductible?", "Yes, 80G certified."), f("Can I volunteer?", "Absolutely! Sign up on our website.") ],
    pages: ["hero", "programs", "impact", "testimonials", "faq", "donate"],
  },
  {
    id: "saas-landing", industry: "SaaS Startup", persona: "Agency",
    audience: "Businesses, developers, enterprises",
    brand: { name: "CloudFlow", tagline: "Automate Everything", voice: "Modern, efficient",
      palette: { primary: "#6366F1", secondary: "#8B5CF6" } },
    content: { bio: "Next-generation workflow automation platform for modern teams.", hero: "Workflows That Work For You.", about: "Connect your tools, automate repetitive tasks, and focus on what matters.", seoTitle: "CloudFlow | Workflow Automation Platform", seoDesc: "Automate your workflows with CloudFlow." },
    products: [ p("Starter Plan", 999, "Up to 10 workflows"), p("Pro Plan", 4999, "Unlimited workflows"), p("Enterprise", 19999, "Custom integrations") ],
    testimonials: [ t("DevTeam Inc.", "Saved 20 hours per week."), t("AgencyFlow", "Our clients love the automation") ],
    faq: [ f("Do you offer a free trial?", "Yes, 14 days."), f("What integrations do you support?", "Slack, GitHub, Jira, Notion, +50 more.") ],
    pages: ["hero", "features", "pricing", "testimonials", "faq"],
  },
  {
    id: "influencer-creator", industry: "Influencer / Creator", persona: "Creator",
    audience: "Fans, brands, followers",
    brand: { name: "CreatorVerse", tagline: "Create. Connect. Grow.", voice: "Authentic, engaging",
      palette: { primary: "#EC4899", secondary: "#8B5CF6" } },
    content: { bio: "Content creator sharing lifestyle, tech, and creativity with a growing community.", hero: "Welcome to My World.", about: "From daily vlogs to deep-dive tutorials — authentic content that connects.", seoTitle: "Content Creator | Lifestyle & Tech", seoDesc: "Content creator sharing lifestyle and tech." },
    products: [ p("Preset Bundle", 999, "10 Lightroom presets"), p("Content Calendar Template", 599, "Notion template"), p("1-on-1 Creator Coaching", 2999, "Grow your channel") ],
    testimonials: [ t("Fan Priya", "Your content made me start creating!"), t("BrandX", "Our best influencer collab") ],
    faq: [ f("What gear do you use?", "Sony A7III + 24-70mm."), f("Do you do brand deals?", "Yes, DM for inquiries.") ],
    pages: ["hero", "content", "about", "testimonials", "faq"],
  },
];
