/**
 * Navigation / Section Graph Reconciliation — RCCF-72.11.
 *
 * Navigation is reconciled against the CANONICAL renderable section graph (the
 * set of section bases that actually render in the published storefront), NOT
 * against content counts. This closes:
 *   S2 — one-shot stale auto-nav (nav now regenerates from the graph)
 *   S3 — unconditional dead "Contact" anchor (Contact only when it renders)
 *
 * Manual / generated distinction:
 *   - Auto-generated section anchors carry `generatedFromSection` and may be
 *     added/removed as the graph changes.
 *   - Items WITHOUT it (page / external / manually authored anchors, and legacy
 *     items that cannot be confidently classified as generated) are user-authored
 *     and are NEVER removed automatically.
 * Legacy items generated by the old content-count system are classified as
 * generated ONLY when they match the exact, deterministic generated signature —
 * otherwise they are preserved as user-authored.
 *
 * `renderableNavBases` receives ALREADY-COMPOSED sections (the output of
 * `LayoutEngine.resolve`, which sets `hasContent`/`visibilityMode`) so the nav
 * graph matches the live render exactly — no duplicated composition logic here.
 */
import type { NavigationItem, WebsiteAggregate } from "@/types/snapshot";
import { resolveRenderableSections } from "@/lib/storefront/section-pipeline";
import { baseOf } from "@/modules/section-presentation";
import type { GoalProfile } from "@/modules/goals-runtime";

/**
 * The section bases that may produce a top-level navigation anchor. Rendered
 * sections outside this set (footer, newsletter, courses, services, bookings,
 * embed, social, affiliateLinks) are intentionally NOT top-level nav items.
 */
export const NAV_GENERATABLE_BASES: ReadonlySet<string> = new Set([
  "hero",
  "products",
  "gallery",
  "timeline",
  "testimonials",
  "faq",
  "games",
  "contentFeed",
  "links",
  "contact",
]);

/** Deterministic generated-anchor signature (id → label/href). */
export const GENERATED_ANCHOR_SIGNATURES: Readonly<Record<string, { label: string; href: string }>> = {
  hero: { label: "Home", href: "#hero" },
  products: { label: "Products", href: "#products" },
  gallery: { label: "Gallery", href: "#gallery" },
  timeline: { label: "Timeline", href: "#timeline" },
  testimonials: { label: "Testimonials", href: "#testimonials" },
  faq: { label: "FAQ", href: "#faq" },
  games: { label: "Games", href: "#games" },
  contentFeed: { label: "Content", href: "#contentFeed" },
  links: { label: "Links", href: "#links" },
  contact: { label: "Contact", href: "#contact" },
};

export interface RenderableNavSection {
  moduleId: string;
  visible?: boolean;
  config: Record<string, unknown>;
}

/**
 * Is this item a generated section anchor? True when it carries explicit
 * `generatedFromSection` metadata, OR (legacy) when it exactly matches the
 * deterministic generated signature (id + href + label + anchor type). Items
 * that do not match — including any user-renamed/reordered/custom anchor — are
 * treated as user-authored and preserved.
 */
export function isGeneratedSectionAnchor(item: NavigationItem): boolean {
  if (item.generatedFromSection) return true;
  if (item.type !== "anchor") return false;
  const sig = GENERATED_ANCHOR_SIGNATURES[item.id];
  if (!sig) return false;
  return item.href === sig.href && item.label === sig.label;
}

/** The base a generated anchor is tied to (its `generatedFromSection` or its id). */
function generatedBase(item: NavigationItem): string {
  return item.generatedFromSection ?? item.id;
}

/**
 * Reduce an already-composed, renderable section list to the ordered, deduped,
 * nav-generatable section bases. `resolveRenderableSections` applies the SAME
 * visibility/empty filter the live storefront uses, so a base is only nav-
 * reachable when it actually renders.
 */
export function renderableNavBases(
  sections: RenderableNavSection[],
  aggregate: WebsiteAggregate,
  goalProfilePresent: boolean,
): string[] {
  const goalProfile: GoalProfile | null = goalProfilePresent
    ? { weights: [], updatedAt: "", source: "manual", entityType: "" }
    : null;
  const renderable = resolveRenderableSections(sections, { goalProfile, aggregate });
  const seen = new Set<string>();
  const out: string[] = [];
  for (const s of renderable) {
    const base = baseOf(s.moduleId);
    if (!NAV_GENERATABLE_BASES.has(base)) continue;
    if (seen.has(base)) continue;
    seen.add(base);
    out.push(base);
  }
  return out;
}

/**
 * Build the default (initial / reset) navigation from a renderable section
 * graph. Home/hero is emitted first (existing product semantics); every other
 * generated anchor follows the graph order. Contact is emitted ONLY when a
 * contact section renders. No content-count derivation.
 */
export function generateDefaultNavigation(graphBases: string[]): NavigationItem[] {
  const bases = [...graphBases];
  const heroIdx = bases.indexOf("hero");
  if (heroIdx >= 0) {
    const hero = bases.splice(heroIdx, 1)[0]!;
    bases.unshift(hero);
  }
  const nav: NavigationItem[] = [];
  let order = 0;
  for (const base of bases) {
    const sig = GENERATED_ANCHOR_SIGNATURES[base];
    if (!sig) continue;
    nav.push({
      id: base,
      label: sig.label,
      href: sig.href,
      type: "anchor",
      order: order++,
      visible: true,
      generatedFromSection: base,
    });
  }
  return nav;
}

/**
 * Reconcile the existing persisted navigation against the current renderable
 * section graph. Pure (no persistence).
 *
 *   - Items keep their original relative order (user reordering is never
 *     clobbered).
 *   - Generated anchors whose base is no longer renderable are removed.
 *   - Newly-appeared renderable bases are appended as generated anchors, in
 *     graph order (never alphabetically).
 *   - User-authored items (page / external / manual anchors / legacy-unclassified)
 *     are preserved, never removed.
 *   - `order` is reassigned sequentially to preserve the RCCF-AUDIT-10B parity
 *     invariant (persisted == snapshot == live DOM).
 */
export function reconcileNavigation(existing: NavigationItem[], graphBases: string[]): NavigationItem[] {
  const inGraph = new Set(graphBases);
  const kept: NavigationItem[] = [];
  const keptBases = new Set<string>();
  for (const item of existing) {
    if (isGeneratedSectionAnchor(item)) {
      const base = generatedBase(item);
      // Drop stale generated anchors whose section no longer renders.
      if (!inGraph.has(base)) continue;
      keptBases.add(base);
    }
    kept.push(item);
  }

  // Append generated anchors for graph bases not yet represented (and not
  // already supplied by a user-authored anchor of the same base).
  const additions: NavigationItem[] = [];
  for (const base of graphBases) {
    if (keptBases.has(base)) continue;
    if (kept.some((m) => m.type === "anchor" && (m.generatedFromSection ?? m.id) === base)) continue;
    const sig = GENERATED_ANCHOR_SIGNATURES[base];
    if (!sig) continue;
    additions.push({
      id: base,
      label: sig.label,
      href: sig.href,
      type: "anchor",
      order: 0,
      visible: true,
      generatedFromSection: base,
    });
  }

  return [...kept, ...additions].map((item, i) => ({ ...item, order: i }));
}
