// ── Recommendation Registry (Phase 1) ──────────────────────
// One canonical registry of recommendations. Every entry declares its
// trigger, its completion condition, its expected impact, its goal affinity,
// its knowledge/success dependencies, and its actions. The engine, categories,
// dashboard, builder, history and analytics ALL derive from this registry.
//
// Everything is a pure predicate over the RecommendationContext — the runtime
// never owns data and never invents recommendations.

import { getField } from "@/modules/knowledge-runtime";
import type { RecommendationContext, RecommendationDefinition } from "./types";

const fieldComplete = (ctx: RecommendationContext, fieldId: string): boolean =>
  getField(fieldId)?.complete(ctx.snapshot) ?? false;

const goalActive = (ctx: RecommendationContext, goalId: string): boolean =>
  ctx.activeProfile?.weights.some((w) => w.goalId === goalId && w.weight > 0) ?? false;

const declaredTruthy = (ctx: RecommendationContext, key: string): boolean =>
  ctx.snapshot.declared[key] === true ||
  (typeof ctx.snapshot.declared[key] === "string" && ctx.snapshot.declared[key].trim().length > 0);

const always = () => true;

export const RECOMMENDATION_REGISTRY: RecommendationDefinition[] = [
  // ── Brand / Identity ──────────────────────────────────────
  {
    id: "ADD_LOGO",
    title: "Upload a logo",
    description: "A logo makes your brand memorable and professional.",
    category: "quick_win",
    priority: 2,
    estimatedTime: 1,
    expectedImpact: { knowledge: 4, brand: 8, goalAlignment: 6 },
    prerequisites: [],
    goalAffinity: { BUILD_BRAND: 1 },
    knowledgeDependencies: ["brand.logo"],
    successDependencies: ["logo"],
    storefrontDimensionsAffected: ["knowledge", "brand", "goalAlignment"],
    dashboardAction: { label: "Upload logo", href: "/admin/appearance" },
    builderAction: { label: "Add your logo", moduleId: "hero" },
    adminHref: "/admin/appearance",
    when: always,
    done: (ctx) => fieldComplete(ctx, "brand.logo"),
    reason: () => "A logo (or profile photo) makes your brand memorable.",
  },
  {
    id: "CONFIGURE_BRAND",
    title: "Set brand colors",
    description: "Custom colors make the site feel like your brand.",
    category: "quick_win",
    priority: 2,
    estimatedTime: 5,
    expectedImpact: { knowledge: 3, brand: 6, goalAlignment: 6 },
    prerequisites: [],
    goalAffinity: { BUILD_BRAND: 1 },
    knowledgeDependencies: ["brand.colors"],
    successDependencies: [],
    storefrontDimensionsAffected: ["brand", "goalAlignment"],
    dashboardAction: { label: "Edit theme", href: "/admin/appearance" },
    builderAction: { label: "Set brand colors", moduleId: "hero" },
    adminHref: "/admin/appearance",
    when: always,
    done: (ctx) => fieldComplete(ctx, "brand.colors"),
    reason: () => "Custom colors make the site feel unmistakably yours.",
  },
  {
    id: "WRITE_ABOUT",
    title: "Write your story",
    description: "A strong bio builds trust and ranks in search.",
    category: "quick_win",
    priority: 2,
    estimatedTime: 5,
    expectedImpact: { knowledge: 5, brand: 8, seo: 6, trust: 6, goalAlignment: 8 },
    prerequisites: [],
    goalAffinity: { BUILD_BRAND: 1, INCREASE_TRUST: 0.8 },
    knowledgeDependencies: ["brand.bio"],
    successDependencies: ["hero"],
    storefrontDimensionsAffected: ["knowledge", "brand", "seo", "trust", "goalAlignment"],
    dashboardAction: { label: "Write your bio", href: "/admin/settings" },
    builderAction: { label: "Write your story", moduleId: "hero" },
    adminHref: "/admin/settings",
    when: always,
    done: (ctx) => fieldComplete(ctx, "brand.bio"),
    reason: () => "Tell visitors who you are and who you help.",
  },
  {
    id: "ADD_SOCIAL_LINKS",
    title: "Add social links",
    description: "Link your social profiles so visitors can follow you.",
    category: "quick_win",
    priority: 2,
    estimatedTime: 3,
    expectedImpact: { knowledge: 4, trust: 4, goalAlignment: 5 },
    prerequisites: [],
    goalAffinity: { GROW_YOUTUBE: 0.8, BUILD_COMMUNITY: 0.8 },
    knowledgeDependencies: ["social.links"],
    successDependencies: [],
    storefrontDimensionsAffected: ["trust", "goalAlignment"],
    dashboardAction: { label: "Add social links", href: "/admin/settings" },
    builderAction: { label: "Add social links", moduleId: "links" },
    adminHref: "/admin/settings",
    when: always,
    done: (ctx) => fieldComplete(ctx, "social.links"),
    reason: () => "Social proof and reach start with visible social links.",
  },

  // ── Hero / Media ──────────────────────────────────────────
  {
    id: "UPLOAD_HERO_IMAGE",
    title: "Add hero media",
    description: "A hero video or image is the first thing visitors see.",
    category: "critical",
    priority: 1,
    estimatedTime: 3,
    expectedImpact: { knowledge: 5, brand: 10, goalAlignment: 5 },
    prerequisites: [],
    goalAffinity: { SHOW_PORTFOLIO: 0.7, BUILD_BRAND: 0.6 },
    knowledgeDependencies: ["media.heroMedia"],
    successDependencies: ["hero"],
    storefrontDimensionsAffected: ["knowledge", "brand", "accessibility"],
    dashboardAction: { label: "Add hero media", href: "/admin/settings" },
    builderAction: { label: "Add hero media", moduleId: "hero" },
    adminHref: "/admin/settings",
    when: always,
    done: (ctx) => fieldComplete(ctx, "media.heroMedia"),
    reason: () => "A strong hero is the highest-leverage first impression.",
  },

  // ── Commerce ──────────────────────────────────────────────
  {
    id: "CREATE_FIRST_PRODUCT",
    title: "Create your first product",
    description: "Give visitors something to buy — a product or offer.",
    category: "critical",
    priority: 1,
    estimatedTime: 5,
    expectedImpact: { knowledge: 8, commerce: 15, goalAlignment: 10 },
    prerequisites: [],
    goalAffinity: { SELL_PRODUCTS: 1, MONETIZE_CONTENT: 0.8 },
    knowledgeDependencies: ["commerce.products"],
    successDependencies: ["product"],
    storefrontDimensionsAffected: ["commerce", "knowledge", "goalAlignment"],
    dashboardAction: { label: "Create product", href: "/admin/products" },
    builderAction: { label: "Add your products", moduleId: "products" },
    adminHref: "/admin/products",
    when: always,
    done: (ctx) => fieldComplete(ctx, "commerce.products"),
    reason: () => "You have no products yet — add one to start selling.",
  },
  {
    id: "CREATE_DIGITAL_PRODUCT",
    title: "Polish your products",
    description: "Products with descriptions and photos sell far better.",
    category: "optimization",
    priority: 4,
    estimatedTime: 15,
    expectedImpact: { knowledge: 4, commerce: 8, goalAlignment: 4 },
    prerequisites: ["CREATE_FIRST_PRODUCT"],
    goalAffinity: { SELL_PRODUCTS: 0.8, MONETIZE_CONTENT: 0.8 },
    knowledgeDependencies: ["commerce.productImages", "commerce.productDescriptions"],
    successDependencies: ["product"],
    storefrontDimensionsAffected: ["commerce", "knowledge"],
    dashboardAction: { label: "Add product photos", href: "/admin/products" },
    builderAction: { label: "Add product photos", moduleId: "products" },
    adminHref: "/admin/products",
    when: (ctx) => ctx.metrics.productCount > 0,
    done: (ctx) =>
      fieldComplete(ctx, "commerce.productImages") && fieldComplete(ctx, "commerce.productDescriptions"),
    reason: () => "Your products exist — add photos and descriptions to convert better.",
  },
  {
    id: "CREATE_FIRST_SERVICE",
    title: "Add a service",
    description: "Offer coaching, consulting or a service package.",
    category: "high_impact",
    priority: 2,
    estimatedTime: 5,
    expectedImpact: { knowledge: 5, commerce: 10, goalAlignment: 10 },
    prerequisites: [],
    goalAffinity: { SELL_SERVICES: 1, FIND_CLIENTS: 0.8, GENERATE_LEADS: 0.8 },
    knowledgeDependencies: ["commerce.services"],
    successDependencies: ["product"],
    storefrontDimensionsAffected: ["commerce", "goalAlignment"],
    dashboardAction: { label: "Add a service", href: "/admin/services" },
    builderAction: { label: "List your services", moduleId: "services" },
    adminHref: "/admin/services",
    when: always,
    done: (ctx) => fieldComplete(ctx, "commerce.services"),
    reason: () => "Services turn your expertise into a sellable offer.",
  },
  {
    id: "ENABLE_BOOKINGS",
    title: "Enable bookings",
    description: "Let visitors reserve your time directly.",
    category: "high_impact",
    priority: 2,
    estimatedTime: 5,
    expectedImpact: { knowledge: 6, commerce: 12, goalAlignment: 12 },
    prerequisites: [],
    goalAffinity: { GET_BOOKINGS: 1 },
    knowledgeDependencies: ["commerce.bookings"],
    successDependencies: ["booking"],
    storefrontDimensionsAffected: ["commerce", "goalAlignment"],
    dashboardAction: { label: "Enable bookings", href: "/admin/bookings" },
    builderAction: { label: "Add a booking form", moduleId: "contact" },
    adminHref: "/admin/bookings",
    when: always,
    done: (ctx) => fieldComplete(ctx, "commerce.bookings"),
    reason: () => "Bookings let visitors reserve your time without asking.",
  },
  {
    id: "CREATE_COURSE",
    title: "Publish a course",
    description: "Package your knowledge into a sellable course.",
    category: "growth",
    priority: 3,
    estimatedTime: 15,
    expectedImpact: { knowledge: 5, commerce: 10, goalAlignment: 12 },
    prerequisites: [],
    goalAffinity: { SELL_COURSES: 1 },
    knowledgeDependencies: ["commerce.courses"],
    successDependencies: ["product"],
    storefrontDimensionsAffected: ["commerce", "goalAlignment"],
    dashboardAction: { label: "Add a course", href: "/admin/courses" },
    builderAction: { label: "Add your courses", moduleId: "courses" },
    adminHref: "/admin/courses",
    when: (ctx) => goalActive(ctx, "SELL_COURSES") || ctx.snapshot.entityType === "educator",
    done: (ctx) => fieldComplete(ctx, "commerce.courses"),
    reason: () => "Courses monetize your knowledge at scale.",
  },
  {
    id: "CREATE_AFFILIATE_PRODUCT",
    title: "Add affiliate links",
    description: "Earn commission on things you already recommend.",
    category: "optimization",
    priority: 4,
    estimatedTime: 5,
    expectedImpact: { knowledge: 4, commerce: 6, goalAlignment: 6 },
    prerequisites: [],
    goalAffinity: { MONETIZE_CONTENT: 1 },
    knowledgeDependencies: ["social.affiliateLinks"],
    successDependencies: [],
    storefrontDimensionsAffected: ["commerce", "goalAlignment"],
    dashboardAction: { label: "Add affiliate links", href: "/admin/links" },
    builderAction: { label: "Add affiliate links", moduleId: "links" },
    adminHref: "/admin/links",
    when: (ctx) => ctx.metrics.productCount > 0 || goalActive(ctx, "MONETIZE_CONTENT"),
    done: (ctx) => fieldComplete(ctx, "social.affiliateLinks"),
    reason: () => "Affiliate links monetize your existing audience.",
  },

  // ── Content / Trust ───────────────────────────────────────
  {
    id: "UPLOAD_GALLERY",
    title: "Build your gallery",
    description: "Add images or videos to showcase your work.",
    category: "high_impact",
    priority: 2,
    estimatedTime: 4,
    expectedImpact: { knowledge: 5, content: 10, goalAlignment: 12 },
    prerequisites: [],
    goalAffinity: { SHOW_PORTFOLIO: 1, FIND_CLIENTS: 0.7 },
    knowledgeDependencies: ["content.gallery"],
    successDependencies: ["gallery"],
    storefrontDimensionsAffected: ["content", "goalAlignment"],
    dashboardAction: { label: "Upload images", href: "/admin/gallery" },
    builderAction: { label: "Add gallery images", moduleId: "gallery" },
    adminHref: "/admin/gallery",
    when: always,
    done: (ctx) => fieldComplete(ctx, "content.gallery"),
    reason: () => "A strong gallery proves your work at a glance.",
  },
  {
    id: "ADD_TESTIMONIALS",
    title: "Add testimonials",
    description: "Social proof convinces undecided visitors.",
    category: "high_impact",
    priority: 1,
    estimatedTime: 5,
    expectedImpact: { knowledge: 6, trust: 14, goalAlignment: 12 },
    prerequisites: [],
    goalAffinity: { INCREASE_TRUST: 1 },
    knowledgeDependencies: ["trust.testimonials"],
    successDependencies: [],
    storefrontDimensionsAffected: ["trust", "goalAlignment"],
    dashboardAction: { label: "Add a testimonial", href: "/admin/testimonials" },
    builderAction: { label: "Add testimonials", moduleId: "testimonials" },
    adminHref: "/admin/testimonials",
    when: always,
    done: (ctx) => fieldComplete(ctx, "trust.testimonials"),
    reason: () => "Testimonials are the strongest trust signal you can add.",
  },
  {
    id: "CREATE_FAQ",
    title: "Add an FAQ",
    description: "Answer common questions to reduce friction.",
    category: "growth",
    priority: 3,
    estimatedTime: 5,
    expectedImpact: { knowledge: 4, seo: 6, trust: 4 },
    prerequisites: [],
    goalAffinity: {},
    knowledgeDependencies: ["content.faq"],
    successDependencies: [],
    storefrontDimensionsAffected: ["seo", "trust"],
    dashboardAction: { label: "Add an FAQ", href: "/admin/faq" },
    builderAction: { label: "Add an FAQ", moduleId: "faq" },
    adminHref: "/admin/faq",
    when: always,
    done: (ctx) => fieldComplete(ctx, "content.faq"),
    reason: () => "A short FAQ removes the most common objections.",
  },
  {
    id: "ADD_TIMELINE",
    title: "Add milestones",
    description: "Share your journey with milestones and achievements.",
    category: "growth",
    priority: 3,
    estimatedTime: 5,
    expectedImpact: { knowledge: 4, trust: 8, goalAlignment: 6 },
    prerequisites: [],
    goalAffinity: { INCREASE_TRUST: 0.8, SHOW_PORTFOLIO: 0.6, BUILD_BRAND: 0.6 },
    knowledgeDependencies: ["trust.timeline"],
    successDependencies: ["gallery"],
    storefrontDimensionsAffected: ["trust", "goalAlignment"],
    dashboardAction: { label: "Add milestones", href: "/admin/milestones" },
    builderAction: { label: "Add milestones", moduleId: "timeline" },
    adminHref: "/admin/milestones",
    when: always,
    done: (ctx) => fieldComplete(ctx, "trust.timeline"),
    reason: () => "Milestones make your credibility visible.",
  },

  // ── SEO / Contact / Platform ──────────────────────────────
  {
    id: "ENABLE_SEO",
    title: "Set up SEO",
    description: "Configure titles and descriptions for search engines.",
    category: "high_impact",
    priority: 2,
    estimatedTime: 10,
    expectedImpact: { knowledge: 6, seo: 8, goalAlignment: 6 },
    prerequisites: [],
    goalAffinity: { BUILD_BRAND: 0.5 },
    knowledgeDependencies: ["seo.title"],
    successDependencies: [],
    storefrontDimensionsAffected: ["seo", "knowledge"],
    dashboardAction: { label: "Set up SEO", href: "/admin/seo" },
    builderAction: { label: "Set up SEO", moduleId: null },
    adminHref: "/admin/seo",
    when: always,
    done: (ctx) => fieldComplete(ctx, "seo.title"),
    reason: () => "Search engines reward clear titles and descriptions.",
  },
  {
    id: "COMPLETE_CONTACT",
    title: "Add contact details",
    description: "A public contact email makes you reachable.",
    category: "high_impact",
    priority: 2,
    estimatedTime: 2,
    expectedImpact: { knowledge: 5, trust: 6, goalAlignment: 6 },
    prerequisites: [],
    goalAffinity: { GENERATE_LEADS: 0.9, FIND_CLIENTS: 0.8 },
    knowledgeDependencies: ["contact.email"],
    successDependencies: [],
    storefrontDimensionsAffected: ["trust", "goalAlignment"],
    dashboardAction: { label: "Add contact email", href: "/admin/profile" },
    builderAction: { label: "Add contact details", moduleId: "contact" },
    adminHref: "/admin/profile",
    when: always,
    done: (ctx) => fieldComplete(ctx, "contact.email"),
    reason: () => "Visitors convert when they can reach you directly.",
  },
  {
    id: "CONNECT_DOMAIN",
    title: "Connect a custom domain",
    description: "Use your own domain for a professional presence.",
    category: "growth",
    priority: 3,
    estimatedTime: 10,
    expectedImpact: { knowledge: 3, brand: 5, seo: 5, goalAlignment: 4 },
    prerequisites: ["PUBLISH_SITE"],
    goalAffinity: { BUILD_BRAND: 0.6 },
    knowledgeDependencies: ["business.domain"],
    successDependencies: ["domain"],
    storefrontDimensionsAffected: ["brand", "seo"],
    dashboardAction: { label: "Connect domain", href: "/admin/settings/domain" },
    builderAction: { label: "Connect a domain", moduleId: null },
    adminHref: "/admin/settings/domain",
    when: (ctx) => ctx.metrics.published,
    done: (ctx) => fieldComplete(ctx, "business.domain"),
    reason: () => "A custom domain makes your brand look established.",
  },
  {
    id: "CONNECT_YOUTUBE",
    title: "Connect your content feed",
    description: "Keep your site fresh with your latest content.",
    category: "growth",
    priority: 3,
    estimatedTime: 3,
    expectedImpact: { knowledge: 4, content: 6, goalAlignment: 6 },
    prerequisites: [],
    goalAffinity: { GROW_YOUTUBE: 1 },
    knowledgeDependencies: ["social.feed"],
    successDependencies: [],
    storefrontDimensionsAffected: ["content", "goalAlignment"],
    dashboardAction: { label: "Connect your feed", href: "/admin/settings/content" },
    builderAction: { label: "Connect your feed", moduleId: "contentFeed" },
    adminHref: "/admin/settings/content",
    when: (ctx) => goalActive(ctx, "GROW_YOUTUBE") || goalActive(ctx, "BUILD_COMMUNITY"),
    done: (ctx) => fieldComplete(ctx, "social.feed"),
    reason: () => "A connected feed keeps your storefront fresh automatically.",
  },

  // ── Audience / Monetization ───────────────────────────────
  {
    id: "ENABLE_NEWSLETTER",
    title: "Add a newsletter",
    description: "Grow an owned audience with email signups.",
    category: "optimization",
    priority: 4,
    estimatedTime: 10,
    expectedImpact: { knowledge: 4, goalAlignment: 8 },
    prerequisites: [],
    goalAffinity: { BUILD_EMAIL_LIST: 1, GROW_YOUTUBE: 0.5 },
    knowledgeDependencies: [],
    successDependencies: [],
    storefrontDimensionsAffected: ["goalAlignment"],
    dashboardAction: { label: "Add newsletter block", href: "/builder" },
    builderAction: { label: "Add a newsletter block", moduleId: "newsletter" },
    adminHref: "/builder",
    when: (ctx) => goalActive(ctx, "BUILD_EMAIL_LIST") || goalActive(ctx, "BUILD_COMMUNITY"),
    done: (ctx) => declaredTruthy(ctx, "newsletter_enabled"),
    reason: () => "An owned email list is the most durable asset you can build.",
  },
  {
    id: "ENABLE_COMMUNITY",
    title: "Build your community",
    description: "Link your community channels (Discord, groups, feed).",
    category: "growth",
    priority: 3,
    estimatedTime: 10,
    expectedImpact: { knowledge: 3, goalAlignment: 8 },
    prerequisites: [],
    goalAffinity: { BUILD_COMMUNITY: 1 },
    knowledgeDependencies: [],
    successDependencies: [],
    storefrontDimensionsAffected: ["goalAlignment"],
    dashboardAction: { label: "Connect community", href: "/admin/settings/content" },
    builderAction: { label: "Add community links", moduleId: "contentFeed" },
    adminHref: "/admin/settings/content",
    when: (ctx) => goalActive(ctx, "BUILD_COMMUNITY") || goalActive(ctx, "BUILD_EMAIL_LIST"),
    done: (ctx) => declaredTruthy(ctx, "community_hub") || ctx.metrics.contentFeedCount > 0,
    reason: () => "Community drives referrals and repeat visits.",
  },
  {
    id: "ADD_REFUND_POLICY",
    title: "Add a refund policy",
    description: "A clear refund policy removes purchase risk.",
    category: "optimization",
    priority: 4,
    estimatedTime: 10,
    expectedImpact: { knowledge: 3, commerce: 4, trust: 6, goalAlignment: 5 },
    prerequisites: [],
    goalAffinity: { SELL_PRODUCTS: 0.7, INCREASE_TRUST: 0.7 },
    knowledgeDependencies: [],
    successDependencies: [],
    storefrontDimensionsAffected: ["commerce", "trust"],
    dashboardAction: { label: "Add refund policy", href: "/admin/knowledge" },
    builderAction: { label: "Add a refund policy", moduleId: null },
    adminHref: "/admin/knowledge",
    when: (ctx) => ctx.metrics.productCount > 0 || goalActive(ctx, "SELL_PRODUCTS"),
    done: (ctx) => declaredTruthy(ctx, "refund_policy"),
    reason: () => "Buyers convert faster when returns are spelled out.",
  },

  // ── Platform / Analytics ──────────────────────────────────
  {
    id: "PUBLISH_SITE",
    title: "Publish your website",
    description: "Make your storefront live so visitors can find it.",
    category: "critical",
    priority: 1,
    estimatedTime: 2,
    expectedImpact: { knowledge: 5, goalAlignment: 10 },
    prerequisites: [],
    goalAffinity: {},
    knowledgeDependencies: [],
    successDependencies: ["publish"],
    storefrontDimensionsAffected: ["goalAlignment"],
    dashboardAction: { label: "Publish website", href: "/builder" },
    builderAction: { label: "Publish your website", moduleId: null },
    adminHref: "/builder",
    when: always,
    done: (ctx) => ctx.metrics.published,
    reason: () => "Nothing converts until your site is live.",
  },
  {
    id: "ENABLE_ANALYTICS",
    title: "Start tracking analytics",
    description: "Understand what's working once you start selling.",
    category: "advanced",
    priority: 4,
    estimatedTime: 2,
    expectedImpact: { knowledge: 2, goalAlignment: 3 },
    prerequisites: ["PUBLISH_SITE"],
    goalAffinity: {},
    knowledgeDependencies: [],
    successDependencies: [],
    storefrontDimensionsAffected: ["goalAlignment"],
    dashboardAction: { label: "View analytics", href: "/admin/analytics" },
    builderAction: { label: "Track analytics", moduleId: null },
    adminHref: "/admin/analytics",
    when: (ctx) => ctx.metrics.published && ctx.metrics.productCount > 0,
    done: (ctx) => ctx.metrics.analyticsActive,
    reason: () => "Measure before you optimise — analytics shows what works.",
  },
  {
    id: "VERIFY_EMAIL",
    title: "Verify your contact email",
    description: "A verified contact email builds buyer confidence.",
    category: "advanced",
    priority: 5,
    estimatedTime: 2,
    expectedImpact: { knowledge: 2, trust: 3, goalAlignment: 2 },
    prerequisites: [],
    goalAffinity: {},
    knowledgeDependencies: ["contact.email"],
    successDependencies: [],
    storefrontDimensionsAffected: ["trust"],
    dashboardAction: { label: "Update contact email", href: "/admin/profile" },
    builderAction: { label: "Verify contact email", moduleId: "contact" },
    adminHref: "/admin/profile",
    when: (ctx) => ctx.metrics.orderCount > 0 || ctx.metrics.productCount > 0,
    done: (ctx) => declaredTruthy(ctx, "email_verified"),
    reason: () => "A verified email reassures buyers and partners.",
  },
];

const REGISTRY_BY_ID = new Map(RECOMMENDATION_REGISTRY.map((r) => [r.id, r]));

export function getRecommendation(id: string): RecommendationDefinition | undefined {
  return REGISTRY_BY_ID.get(id);
}

export function isKnownRecommendation(id: string): boolean {
  return REGISTRY_BY_ID.has(id);
}
